// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package ledger

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
WITH upserted AS (
  INSERT INTO ledger_members (ledger_id, user_id, role, updated_at)
  VALUES ($1, $2, $3, $4)
  ON CONFLICT (ledger_id, user_id) DO UPDATE
  SET role = EXCLUDED.role,
    removed_at = NULL,
    updated_at = EXCLUDED.updated_at
  WHERE ledger_members.removed_at IS NOT NULL
  RETURNING ledger_id, user_id, role, created_at, updated_at
)
SELECT upserted.ledger_id, upserted.user_id, upserted.role, upserted.created_at, upserted.updated_at,
  COALESCE(u.display_name, '') AS display_name,
  u.email,
  u.avatar_url
FROM upserted
JOIN users u ON u.id = upserted.user_id
`

type AddMemberParams struct {
	LedgerID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	UpdatedAt pgtype.Timestamptz
}

type AddMemberRow struct {
	LedgerID    pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DisplayName string
	Email       string
	AvatarUrl   pgtype.Text
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (AddMemberRow, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.LedgerID,
		arg.UserID,
		arg.Role,
		arg.UpdatedAt,
	)
	var i AddMemberRow
	err := row.Scan(
		&i.LedgerID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
	)
	return i, err
}

const createLedger = `-- name: CreateLedger :one
INSERT INTO ledgers (owner_user_id, name, currency_code)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, name, currency_code, created_at, updated_at
`

type CreateLedgerParams struct {
	OwnerUserID  pgtype.UUID
	Name         string
	CurrencyCode string
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, createLedger, arg.OwnerUserID, arg.Name, arg.CurrencyCode)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLedger = `-- name: DeleteLedger :exec
DELETE FROM ledgers
WHERE id = $1
`

func (q *Queries) DeleteLedger(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLedger, id)
	return err
}

const getLedgerByID = `-- name: GetLedgerByID :one
SELECT id, owner_user_id, name, currency_code, created_at, updated_at
FROM ledgers
WHERE id = $1
`

func (q *Queries) GetLedgerByID(ctx context.Context, id pgtype.UUID) (Ledger, error) {
	row := q.db.QueryRow(ctx, getLedgerByID, id)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerForUser = `-- name: GetLedgerForUser :one
SELECT l.id, l.owner_user_id, l.name, l.currency_code, l.created_at, l.updated_at,
  CASE WHEN l.owner_user_id = $1 THEN 'owner' ELSE lm.role END AS role
FROM ledgers l
LEFT JOIN ledger_members lm ON lm.ledger_id = l.id AND lm.user_id = $1 AND lm.removed_at IS NULL
WHERE l.id = $2 AND (l.owner_user_id = $1 OR lm.user_id = $1)
`

type GetLedgerForUserParams struct {
	OwnerUserID pgtype.UUID
	ID          pgtype.UUID
}

type GetLedgerForUserRow struct {
	ID           pgtype.UUID
	OwnerUserID  pgtype.UUID
	Name         string
	CurrencyCode string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Role         interface{}
}

func (q *Queries) GetLedgerForUser(ctx context.Context, arg GetLedgerForUserParams) (GetLedgerForUserRow, error) {
	row := q.db.QueryRow(ctx, getLedgerForUser, arg.OwnerUserID, arg.ID)
	var i GetLedgerForUserRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getLedgerRole = `-- name: GetLedgerRole :one
SELECT CASE WHEN l.owner_user_id = $1 THEN 'owner' ELSE lm.role END AS role
FROM ledgers l
LEFT JOIN ledger_members lm ON lm.ledger_id = l.id AND lm.user_id = $1 AND lm.removed_at IS NULL
WHERE l.id = $2 AND (l.owner_user_id = $1 OR lm.user_id = $1)
`

type GetLedgerRoleParams struct {
	OwnerUserID pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) GetLedgerRole(ctx context.Context, arg GetLedgerRoleParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLedgerRole, arg.OwnerUserID, arg.ID)
	var role interface{}
	err := row.Scan(&role)
	return role, err
}

const ledgerExists = `-- name: LedgerExists :one
SELECT EXISTS (SELECT 1 FROM ledgers WHERE id = $1) AS exists
`

func (q *Queries) LedgerExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLedgersForUser = `-- name: ListLedgersForUser :many

SELECT l.id, l.owner_user_id, l.name, l.currency_code, l.created_at, l.updated_at,
  CASE WHEN l.owner_user_id = $1 THEN 'owner' ELSE lm.role END AS role
FROM ledgers l
LEFT JOIN ledger_members lm ON lm.ledger_id = l.id AND lm.user_id = $1 AND lm.removed_at IS NULL
WHERE l.owner_user_id = $1 OR lm.user_id = $1
ORDER BY l.created_at DESC
`

type ListLedgersForUserRow struct {
	ID           pgtype.UUID
	OwnerUserID  pgtype.UUID
	Name         string
	CurrencyCode string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Role         interface{}
}

// Ledgers
func (q *Queries) ListLedgersForUser(ctx context.Context, ownerUserID pgtype.UUID) ([]ListLedgersForUserRow, error) {
	rows, err := q.db.Query(ctx, listLedgersForUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgersForUserRow
	for rows.Next() {
		var i ListLedgersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.CurrencyCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many

SELECT lm.ledger_id, lm.user_id, lm.role, lm.created_at, lm.updated_at,
  COALESCE(u.display_name, '') AS display_name,
  u.email,
  u.avatar_url
FROM ledger_members lm
JOIN users u ON u.id = lm.user_id
WHERE lm.ledger_id = $1 AND lm.removed_at IS NULL
ORDER BY lm.created_at
`

type ListMembersRow struct {
	LedgerID    pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DisplayName string
	Email       string
	AvatarUrl   pgtype.Text
}

// Members
func (q *Queries) ListMembers(ctx context.Context, ledgerID pgtype.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.LedgerID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
UPDATE ledger_members
SET removed_at = now(), updated_at = now()
WHERE ledger_id = $1 AND user_id = $2 AND removed_at IS NULL
`

type RemoveMemberParams struct {
	LedgerID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.LedgerID, arg.UserID)
	return err
}

const updateLedger = `-- name: UpdateLedger :one
UPDATE ledgers
SET name = $2, updated_at = $3
WHERE id = $1
RETURNING id, owner_user_id, name, currency_code, created_at, updated_at
`

type UpdateLedgerParams struct {
	ID        pgtype.UUID
	Name      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateLedger(ctx context.Context, arg UpdateLedgerParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, updateLedger, arg.ID, arg.Name, arg.UpdatedAt)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
WITH updated AS (
  UPDATE ledger_members
  SET role = $3, updated_at = $4
  WHERE ledger_id = $1 AND user_id = $2 AND removed_at IS NULL
  RETURNING ledger_id, user_id, role, created_at, updated_at
)
SELECT updated.ledger_id, updated.user_id, updated.role, updated.created_at, updated.updated_at,
  COALESCE(u.display_name, '') AS display_name,
  u.email,
  u.avatar_url
FROM updated
JOIN users u ON u.id = updated.user_id
`

type UpdateMemberRoleParams struct {
	LedgerID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	UpdatedAt pgtype.Timestamptz
}

type UpdateMemberRoleRow struct {
	LedgerID    pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DisplayName string
	Email       string
	AvatarUrl   pgtype.Text
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (UpdateMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, updateMemberRole,
		arg.LedgerID,
		arg.UserID,
		arg.Role,
		arg.UpdatedAt,
	)
	var i UpdateMemberRoleRow
	err := row.Scan(
		&i.LedgerID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
	)
	return i, err
}
