// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package accounts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (ledger_id, name, type, nature, is_active, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ledger_id, name, type, nature, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	LedgerID  pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
}

type CreateAccountRow struct {
	ID        pgtype.UUID
	LedgerID  pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.LedgerID,
		arg.Name,
		arg.Type,
		arg.Nature,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Type,
		&i.Nature,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :one
UPDATE accounts
SET is_active = false, updated_at = $3
WHERE ledger_id = $1 AND id = $2
RETURNING id, ledger_id, name, type, nature, is_active, created_at, updated_at
`

type DeactivateAccountParams struct {
	LedgerID  pgtype.UUID
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

type DeactivateAccountRow struct {
	ID        pgtype.UUID
	LedgerID  pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) DeactivateAccount(ctx context.Context, arg DeactivateAccountParams) (DeactivateAccountRow, error) {
	row := q.db.QueryRow(ctx, deactivateAccount, arg.LedgerID, arg.ID, arg.UpdatedAt)
	var i DeactivateAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Type,
		&i.Nature,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountByType = `-- name: FindAccountByType :one
SELECT id
FROM accounts
WHERE ledger_id = $1 AND type = $2 AND is_active = true
ORDER BY created_at ASC
LIMIT 1
`

type FindAccountByTypeParams struct {
	LedgerID pgtype.UUID
	Type     string
}

func (q *Queries) FindAccountByType(ctx context.Context, arg FindAccountByTypeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAccountByType, arg.LedgerID, arg.Type)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, ledger_id, name, type, nature, is_active, created_at, updated_at
FROM accounts
WHERE ledger_id = $1 AND id = $2
`

type GetAccountByIDParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

type GetAccountByIDRow struct {
	ID        pgtype.UUID
	LedgerID  pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.LedgerID, arg.ID)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Type,
		&i.Nature,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByLedger = `-- name: ListAccountsByLedger :many

SELECT id, ledger_id, name, type, nature, is_active, created_at, updated_at
FROM accounts
WHERE ledger_id = $1
ORDER BY created_at
`

type ListAccountsByLedgerRow struct {
	ID        pgtype.UUID
	LedgerID  pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Accounts
func (q *Queries) ListAccountsByLedger(ctx context.Context, ledgerID pgtype.UUID) ([]ListAccountsByLedgerRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByLedger, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByLedgerRow
	for rows.Next() {
		var i ListAccountsByLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.Name,
			&i.Type,
			&i.Nature,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $3, type = $4, nature = $5, is_active = $6, updated_at = $7
WHERE ledger_id = $1 AND id = $2
RETURNING id, ledger_id, name, type, nature, is_active, created_at, updated_at
`

type UpdateAccountParams struct {
	LedgerID  pgtype.UUID
	ID        pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
}

type UpdateAccountRow struct {
	ID        pgtype.UUID
	LedgerID  pgtype.UUID
	Name      string
	Type      string
	Nature    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.LedgerID,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Nature,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Type,
		&i.Nature,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
