// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package reports

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAccountBalances = `-- name: ListAccountBalances :many

SELECT a.id, a.name, a.type,
  COALESCE(SUM(
    CASE
      WHEN t.id IS NULL THEN 0
      WHEN c.direction = 'in' THEN e.amount_cents
      WHEN c.direction = 'out' THEN -e.amount_cents
      ELSE 0
    END
  ), 0) AS net_cents
FROM accounts a
LEFT JOIN entries e ON e.account_id = a.id AND e.ledger_id = a.ledger_id
LEFT JOIN transactions t ON t.id = e.transaction_id AND t.occurred_at < $2
LEFT JOIN categories c ON c.id = e.category_id
WHERE a.ledger_id = $1
GROUP BY a.id, a.name, a.type
ORDER BY a.created_at
`

type ListAccountBalancesParams struct {
	LedgerID   pgtype.UUID
	OccurredAt pgtype.Timestamptz
}

type ListAccountBalancesRow struct {
	ID       pgtype.UUID
	Name     string
	Type     string
	NetCents interface{}
}

// Reports
func (q *Queries) ListAccountBalances(ctx context.Context, arg ListAccountBalancesParams) ([]ListAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalances, arg.LedgerID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountBalancesRow
	for rows.Next() {
		var i ListAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.NetCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashflow = `-- name: ListCashflow :many
SELECT date_trunc('month', t.occurred_at)::date AS month,
  COALESCE(SUM(CASE WHEN c.direction = 'in' THEN e.amount_cents ELSE 0 END), 0) AS total_in,
  COALESCE(SUM(CASE WHEN c.direction = 'out' THEN e.amount_cents ELSE 0 END), 0) AS total_out
FROM entries e
JOIN transactions t ON t.id = e.transaction_id
JOIN categories c ON c.id = e.category_id
WHERE e.ledger_id = $1 AND t.occurred_at >= $2 AND t.occurred_at <= $3
GROUP BY month
ORDER BY month
`

type ListCashflowParams struct {
	LedgerID     pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

type ListCashflowRow struct {
	Month    pgtype.Date
	TotalIn  interface{}
	TotalOut interface{}
}

func (q *Queries) ListCashflow(ctx context.Context, arg ListCashflowParams) ([]ListCashflowRow, error) {
	rows, err := q.db.Query(ctx, listCashflow, arg.LedgerID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCashflowRow
	for rows.Next() {
		var i ListCashflowRow
		if err := rows.Scan(&i.Month, &i.TotalIn, &i.TotalOut); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategorySummary = `-- name: ListCategorySummary :many
SELECT c.id, c.name, c.direction,
  COALESCE(SUM(
    CASE
      WHEN t.id IS NULL THEN 0
      ELSE e.amount_cents
    END
  ), 0) AS total_cents
FROM categories c
LEFT JOIN entries e ON e.category_id = c.id AND e.ledger_id = c.ledger_id
LEFT JOIN transactions t ON t.id = e.transaction_id AND t.occurred_at >= $2 AND t.occurred_at <= $3
WHERE c.ledger_id = $1
GROUP BY c.id, c.name, c.direction
ORDER BY c.name
`

type ListCategorySummaryParams struct {
	LedgerID     pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

type ListCategorySummaryRow struct {
	ID         pgtype.UUID
	Name       string
	Direction  string
	TotalCents interface{}
}

func (q *Queries) ListCategorySummary(ctx context.Context, arg ListCategorySummaryParams) ([]ListCategorySummaryRow, error) {
	rows, err := q.db.Query(ctx, listCategorySummary, arg.LedgerID, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategorySummaryRow
	for rows.Next() {
		var i ListCategorySummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Direction,
			&i.TotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
