// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package budget

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetLine = `-- name: CreateBudgetLine :one

INSERT INTO budget_plan_lines (version_id, category_id, percent, include_children, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, version_id, category_id, percent, include_children, created_at, updated_at
`

type CreateBudgetLineParams struct {
	VersionID       pgtype.UUID
	CategoryID      pgtype.UUID
	Percent         pgtype.Numeric
	IncludeChildren bool
	UpdatedAt       pgtype.Timestamptz
}

// Budget lines
func (q *Queries) CreateBudgetLine(ctx context.Context, arg CreateBudgetLineParams) (BudgetPlanLine, error) {
	row := q.db.QueryRow(ctx, createBudgetLine,
		arg.VersionID,
		arg.CategoryID,
		arg.Percent,
		arg.IncludeChildren,
		arg.UpdatedAt,
	)
	var i BudgetPlanLine
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.CategoryID,
		&i.Percent,
		&i.IncludeChildren,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBudgetPlan = `-- name: CreateBudgetPlan :one
INSERT INTO budget_plans (ledger_id, name, updated_at)
VALUES ($1, $2, $3)
RETURNING id, ledger_id, name, created_at, updated_at
`

type CreateBudgetPlanParams struct {
	LedgerID  pgtype.UUID
	Name      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateBudgetPlan(ctx context.Context, arg CreateBudgetPlanParams) (BudgetPlan, error) {
	row := q.db.QueryRow(ctx, createBudgetPlan, arg.LedgerID, arg.Name, arg.UpdatedAt)
	var i BudgetPlan
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBudgetVersion = `-- name: CreateBudgetVersion :one

INSERT INTO budget_plan_versions (plan_id, effective_from_month, created_by_user_id, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, plan_id, effective_from_month, created_by_user_id, created_at, updated_at
`

type CreateBudgetVersionParams struct {
	PlanID             pgtype.UUID
	EffectiveFromMonth pgtype.Date
	CreatedByUserID    pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
}

// Budget versions
func (q *Queries) CreateBudgetVersion(ctx context.Context, arg CreateBudgetVersionParams) (BudgetPlanVersion, error) {
	row := q.db.QueryRow(ctx, createBudgetVersion,
		arg.PlanID,
		arg.EffectiveFromMonth,
		arg.CreatedByUserID,
		arg.UpdatedAt,
	)
	var i BudgetPlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.EffectiveFromMonth,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudgetLine = `-- name: DeleteBudgetLine :exec
DELETE FROM budget_plan_lines
WHERE id = $1 AND version_id = $2
`

type DeleteBudgetLineParams struct {
	ID        pgtype.UUID
	VersionID pgtype.UUID
}

func (q *Queries) DeleteBudgetLine(ctx context.Context, arg DeleteBudgetLineParams) error {
	_, err := q.db.Exec(ctx, deleteBudgetLine, arg.ID, arg.VersionID)
	return err
}

const deleteBudgetPlan = `-- name: DeleteBudgetPlan :exec
DELETE FROM budget_plans
WHERE ledger_id = $1
`

func (q *Queries) DeleteBudgetPlan(ctx context.Context, ledgerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudgetPlan, ledgerID)
	return err
}

const deleteBudgetVersion = `-- name: DeleteBudgetVersion :exec
DELETE FROM budget_plan_versions
WHERE id = $1
`

func (q *Queries) DeleteBudgetVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudgetVersion, id)
	return err
}

const getApplicableBudgetVersion = `-- name: GetApplicableBudgetVersion :one
SELECT id, plan_id, effective_from_month, created_by_user_id, created_at, updated_at
FROM budget_plan_versions
WHERE plan_id = $1 AND effective_from_month <= $2
ORDER BY effective_from_month DESC
LIMIT 1
`

type GetApplicableBudgetVersionParams struct {
	PlanID             pgtype.UUID
	EffectiveFromMonth pgtype.Date
}

func (q *Queries) GetApplicableBudgetVersion(ctx context.Context, arg GetApplicableBudgetVersionParams) (BudgetPlanVersion, error) {
	row := q.db.QueryRow(ctx, getApplicableBudgetVersion, arg.PlanID, arg.EffectiveFromMonth)
	var i BudgetPlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.EffectiveFromMonth,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetPlanByLedger = `-- name: GetBudgetPlanByLedger :one

SELECT id, ledger_id, name, created_at, updated_at
FROM budget_plans
WHERE ledger_id = $1
`

// Budget plans
func (q *Queries) GetBudgetPlanByLedger(ctx context.Context, ledgerID pgtype.UUID) (BudgetPlan, error) {
	row := q.db.QueryRow(ctx, getBudgetPlanByLedger, ledgerID)
	var i BudgetPlan
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetVersionByID = `-- name: GetBudgetVersionByID :one
SELECT id, plan_id, effective_from_month, created_by_user_id, created_at, updated_at
FROM budget_plan_versions
WHERE id = $1
`

func (q *Queries) GetBudgetVersionByID(ctx context.Context, id pgtype.UUID) (BudgetPlanVersion, error) {
	row := q.db.QueryRow(ctx, getBudgetVersionByID, id)
	var i BudgetPlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.EffectiveFromMonth,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetLinesByVersion = `-- name: ListBudgetLinesByVersion :many
SELECT id, version_id, category_id, percent, include_children, created_at, updated_at
FROM budget_plan_lines
WHERE version_id = $1
ORDER BY created_at
`

func (q *Queries) ListBudgetLinesByVersion(ctx context.Context, versionID pgtype.UUID) ([]BudgetPlanLine, error) {
	rows, err := q.db.Query(ctx, listBudgetLinesByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetPlanLine
	for rows.Next() {
		var i BudgetPlanLine
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.CategoryID,
			&i.Percent,
			&i.IncludeChildren,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetLinesWithCategory = `-- name: ListBudgetLinesWithCategory :many
SELECT l.id, l.version_id, l.category_id, l.percent, l.include_children, l.created_at, l.updated_at,
  c.name, c.direction, c.is_budget_base, c.is_budget_relevant
FROM budget_plan_lines l
JOIN categories c ON c.id = l.category_id
WHERE l.version_id = $1
ORDER BY c.name
`

type ListBudgetLinesWithCategoryRow struct {
	ID               pgtype.UUID
	VersionID        pgtype.UUID
	CategoryID       pgtype.UUID
	Percent          pgtype.Numeric
	IncludeChildren  bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Name             string
	Direction        string
	IsBudgetBase     bool
	IsBudgetRelevant bool
}

func (q *Queries) ListBudgetLinesWithCategory(ctx context.Context, versionID pgtype.UUID) ([]ListBudgetLinesWithCategoryRow, error) {
	rows, err := q.db.Query(ctx, listBudgetLinesWithCategory, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetLinesWithCategoryRow
	for rows.Next() {
		var i ListBudgetLinesWithCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.CategoryID,
			&i.Percent,
			&i.IncludeChildren,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Direction,
			&i.IsBudgetBase,
			&i.IsBudgetRelevant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetVersions = `-- name: ListBudgetVersions :many
SELECT id, plan_id, effective_from_month, created_by_user_id, created_at, updated_at
FROM budget_plan_versions
WHERE plan_id = $1
  AND ($2::date IS NULL OR effective_from_month >= $2)
  AND ($3::date IS NULL OR effective_from_month <= $3)
ORDER BY effective_from_month DESC
`

type ListBudgetVersionsParams struct {
	PlanID  pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) ListBudgetVersions(ctx context.Context, arg ListBudgetVersionsParams) ([]BudgetPlanVersion, error) {
	rows, err := q.db.Query(ctx, listBudgetVersions, arg.PlanID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetPlanVersion
	for rows.Next() {
		var i BudgetPlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.EffectiveFromMonth,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIncomeBase = `-- name: SumIncomeBase :one

SELECT COALESCE(SUM(e.amount_cents), 0) AS income_base_cents
FROM entries e
JOIN transactions t ON t.id = e.transaction_id
JOIN categories c ON c.id = e.category_id
WHERE e.ledger_id = $1
  AND t.occurred_at >= $2 AND t.occurred_at < $3
  AND c.direction = 'in'
  AND c.is_budget_base = true
`

type SumIncomeBaseParams struct {
	LedgerID     pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

// Monthly calculations
func (q *Queries) SumIncomeBase(ctx context.Context, arg SumIncomeBaseParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumIncomeBase, arg.LedgerID, arg.OccurredAt, arg.OccurredAt_2)
	var income_base_cents interface{}
	err := row.Scan(&income_base_cents)
	return income_base_cents, err
}

const sumOutOfBudget = `-- name: SumOutOfBudget :one
SELECT COALESCE(SUM(e.amount_cents), 0) AS spent_cents
FROM entries e
JOIN transactions t ON t.id = e.transaction_id
JOIN categories c ON c.id = e.category_id
WHERE e.ledger_id = $1
  AND t.occurred_at >= $2 AND t.occurred_at < $3
  AND c.direction = 'out'
  AND c.is_budget_relevant = false
`

type SumOutOfBudgetParams struct {
	LedgerID     pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

func (q *Queries) SumOutOfBudget(ctx context.Context, arg SumOutOfBudgetParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumOutOfBudget, arg.LedgerID, arg.OccurredAt, arg.OccurredAt_2)
	var spent_cents interface{}
	err := row.Scan(&spent_cents)
	return spent_cents, err
}

const sumSpentForCategory = `-- name: SumSpentForCategory :one
SELECT COALESCE(SUM(e.amount_cents), 0) AS spent_cents
FROM entries e
JOIN transactions t ON t.id = e.transaction_id
JOIN categories c ON c.id = e.category_id
WHERE e.ledger_id = $1
  AND t.occurred_at >= $2 AND t.occurred_at < $3
  AND c.direction = 'out'
  AND c.is_budget_relevant = true
  AND e.category_id = $4
`

type SumSpentForCategoryParams struct {
	LedgerID     pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
	CategoryID   pgtype.UUID
}

func (q *Queries) SumSpentForCategory(ctx context.Context, arg SumSpentForCategoryParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumSpentForCategory,
		arg.LedgerID,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.CategoryID,
	)
	var spent_cents interface{}
	err := row.Scan(&spent_cents)
	return spent_cents, err
}

const sumSpentForCategoryWithChildren = `-- name: SumSpentForCategoryWithChildren :one
WITH RECURSIVE tree AS (
  SELECT categories.id, categories.parent_id
  FROM categories
  WHERE categories.ledger_id = $1 AND categories.id = $4
  UNION ALL
  SELECT c.id, c.parent_id
  FROM categories c
  JOIN tree t ON t.id = c.parent_id
  WHERE c.ledger_id = $1
)
SELECT COALESCE(SUM(e.amount_cents), 0) AS spent_cents
FROM entries e
JOIN transactions t ON t.id = e.transaction_id
JOIN categories c ON c.id = e.category_id
JOIN tree ON tree.id = c.id
WHERE e.ledger_id = $1
  AND t.occurred_at >= $2 AND t.occurred_at < $3
  AND c.direction = 'out'
  AND c.is_budget_relevant = true
`

type SumSpentForCategoryWithChildrenParams struct {
	LedgerID     pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) SumSpentForCategoryWithChildren(ctx context.Context, arg SumSpentForCategoryWithChildrenParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumSpentForCategoryWithChildren,
		arg.LedgerID,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.ID,
	)
	var spent_cents interface{}
	err := row.Scan(&spent_cents)
	return spent_cents, err
}

const updateBudgetLine = `-- name: UpdateBudgetLine :one
UPDATE budget_plan_lines
SET percent = $3, include_children = $4, updated_at = $5
WHERE id = $1 AND version_id = $2
RETURNING id, version_id, category_id, percent, include_children, created_at, updated_at
`

type UpdateBudgetLineParams struct {
	ID              pgtype.UUID
	VersionID       pgtype.UUID
	Percent         pgtype.Numeric
	IncludeChildren bool
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateBudgetLine(ctx context.Context, arg UpdateBudgetLineParams) (BudgetPlanLine, error) {
	row := q.db.QueryRow(ctx, updateBudgetLine,
		arg.ID,
		arg.VersionID,
		arg.Percent,
		arg.IncludeChildren,
		arg.UpdatedAt,
	)
	var i BudgetPlanLine
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.CategoryID,
		&i.Percent,
		&i.IncludeChildren,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudgetPlan = `-- name: UpdateBudgetPlan :one
UPDATE budget_plans
SET name = $2, updated_at = $3
WHERE ledger_id = $1
RETURNING id, ledger_id, name, created_at, updated_at
`

type UpdateBudgetPlanParams struct {
	LedgerID  pgtype.UUID
	Name      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateBudgetPlan(ctx context.Context, arg UpdateBudgetPlanParams) (BudgetPlan, error) {
	row := q.db.QueryRow(ctx, updateBudgetPlan, arg.LedgerID, arg.Name, arg.UpdatedAt)
	var i BudgetPlan
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
