CREATE TABLE "accounts" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "type" varchar(20) NOT NULL CHECK (type IN ('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE')),
  "currency" char(3) NOT NULL DEFAULT 'BRL',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "parties" (
  "party_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "kind" varchar(30) NOT NULL DEFAULT 'PERSON' CHECK (kind IN ('PERSON', 'ORG', 'SYSTEM')),
  "notes" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "direction" varchar(10) NOT NULL CHECK (direction IN ('IN', 'OUT')),
  "is_budget_relevant" boolean NOT NULL DEFAULT true,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "transactions" (
  "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "occurred_at" date NOT NULL,
  "description" varchar(255) NOT NULL,
  "reference" varchar(100),
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "postings" (
  "posting_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" int NOT NULL,
  "account_id" int NOT NULL,
  "category_id" int,
  "party_id" int,
  "side" varchar(6) NOT NULL CHECK (side IN ('DEBIT', 'CREDIT')),
  "amount" decimal(14,2) NOT NULL CHECK (amount > 0),
  "memo" varchar(255),
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "tags" (
  "tag_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(60) NOT NULL UNIQUE,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "posting_tags" (
  "posting_id" int NOT NULL,
  "tag_id" int NOT NULL,
  PRIMARY KEY ("posting_id", "tag_id")
);

CREATE INDEX "idx_postings_transaction" ON "postings" ("transaction_id");
CREATE INDEX "idx_postings_account" ON "postings" ("account_id");
CREATE INDEX "idx_postings_category" ON "postings" ("category_id");
CREATE INDEX "idx_postings_party" ON "postings" ("party_id");

ALTER TABLE "postings" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id") ON DELETE CASCADE;
ALTER TABLE "postings" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("account_id");
ALTER TABLE "postings" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");
ALTER TABLE "postings" ADD FOREIGN KEY ("party_id") REFERENCES "parties" ("party_id");
ALTER TABLE "posting_tags" ADD FOREIGN KEY ("posting_id") REFERENCES "postings" ("posting_id") ON DELETE CASCADE;
ALTER TABLE "posting_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("tag_id") ON DELETE CASCADE;
