CREATE TABLE "flow_categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "direction" varchar(10) NOT NULL CHECK (direction IN ('IN', 'OUT')),
  "is_budget_relevant" boolean NOT NULL DEFAULT true,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "cash_flows" (
  "cash_flow_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date NOT NULL,
  "category_id" int NOT NULL,
  "direction" varchar(10) NOT NULL CHECK (direction IN ('IN', 'OUT')),
  "title" varchar(255) NOT NULL,
  "amount" decimal(14,2) NOT NULL CHECK (amount > 0)
);

CREATE TABLE "payment_methods" (
  "payment_method_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "kind" varchar(50) NOT NULL,
  "bank_name" varchar(100),
  "closing_day" int,
  "due_day" int,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "expense_details" (
  "expense_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cash_flow_id" int NOT NULL,
  "payment_method_id" int,
  "is_fixed" boolean NOT NULL DEFAULT false,
  "is_future" boolean NOT NULL DEFAULT false,
  "installment_plan_id" int,
  "affects_card_invoice" boolean NOT NULL DEFAULT false
);

CREATE TABLE "installment_plans" (
  "installment_plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(255) NOT NULL,
  "total_amount" decimal(14,2) NOT NULL,
  "installment_count" int NOT NULL,
  "installment_amount" decimal(14,2),
  "start_month" date NOT NULL,
  "payment_method_id" int NOT NULL,
  "starts_on_current_invoice" boolean NOT NULL DEFAULT true
);

CREATE TABLE "budget_periods" (
  "budget_period_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "month" date NOT NULL,
  "analysis_mode" varchar(20),
  "is_closed" boolean NOT NULL DEFAULT false
);

CREATE TABLE "budget_items" (
  "budget_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "budget_period_id" int NOT NULL,
  "category_id" int NOT NULL,
  "mode" varchar(30) NOT NULL,
  "planned_amount" decimal(14,2),
  "target_percent" decimal(5,2),
  "notes" text
);

CREATE TABLE "picuinha_persons" (
  "person_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "notes" text
);

CREATE TABLE "picuinha_entries" (
  "picuinha_entry_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int NOT NULL,
  "date" date NOT NULL,
  "kind" varchar(50) NOT NULL,
  "amount" decimal(14,2) NOT NULL,
  "cash_flow_id" int
);

COMMENT ON TABLE "flow_categories" IS 'Categorias de ENTRADA (ex.: Ganho, Investimento) e de SAÍDA (ex.: Custos Fixos, Prazeres, Veículo/Transporte etc.)';

COMMENT ON TABLE "cash_flows" IS 'Para casos 1,2 e 3 (entradas), você preenche apenas: date, category_id (Ganho/Investimento), title, amount.';

COMMENT ON TABLE "expense_details" IS 'Entradas (Ganhos/Investimentos) NÃO precisam de registro aqui. Apenas saídas mais complexas.';

COMMENT ON TABLE "installment_plans" IS 'As parcelas individuais serão representadas por vários cash_flows (SAÍDAS), cada um amarrado ao installment_plan via expense_details.';

COMMENT ON TABLE "picuinha_entries" IS 'Você terá o saldo por pessoa somando/subtraindo os amounts conforme o kind. O cash_flow_id conecta com o fluxo real (entradas/saídas).';

ALTER TABLE "cash_flows" ADD FOREIGN KEY ("category_id") REFERENCES "flow_categories" ("category_id");

ALTER TABLE "expense_details" ADD FOREIGN KEY ("cash_flow_id") REFERENCES "cash_flows" ("cash_flow_id");

ALTER TABLE "expense_details" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("payment_method_id");

ALTER TABLE "expense_details" ADD FOREIGN KEY ("installment_plan_id") REFERENCES "installment_plans" ("installment_plan_id");

ALTER TABLE "installment_plans" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("payment_method_id");

ALTER TABLE "budget_items" ADD FOREIGN KEY ("budget_period_id") REFERENCES "budget_periods" ("budget_period_id");

ALTER TABLE "budget_items" ADD FOREIGN KEY ("category_id") REFERENCES "flow_categories" ("category_id");

ALTER TABLE "picuinha_entries" ADD FOREIGN KEY ("person_id") REFERENCES "picuinha_persons" ("person_id");

ALTER TABLE "picuinha_entries" ADD FOREIGN KEY ("cash_flow_id") REFERENCES "cash_flows" ("cash_flow_id");
