CREATE TABLE "payment_methods" (
  "payment_method_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int NOT NULL,
  "name" varchar(100) NOT NULL,
  "kind" varchar(50) NOT NULL,
  "bank_name" varchar(100),
  "closing_day" int,
  "due_day" int,
  "credit_limit" decimal(14,2),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "uidx_payment_methods_account" ON "payment_methods" ("account_id");

ALTER TABLE "payment_methods" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("account_id");
