CREATE TABLE "installment_plans" (
  "installment_plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(255) NOT NULL,
  "plan_type" varchar(20) NOT NULL CHECK (plan_type IN ('INSTALLMENT', 'RECURRING')),
  "total_amount" decimal(14,2),
  "installment_count" int,
  "installment_amount" decimal(14,2),
  "start_date" date NOT NULL,
  "payment_method_id" int,
  "account_id" int,
  "category_id" int,
  "party_id" int,
  "interest_rate" decimal(7,4),
  "recurrence_interval_months" int,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CHECK (payment_method_id IS NOT NULL OR account_id IS NOT NULL)
);

CREATE TABLE "installment_plan_items" (
  "installment_plan_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "installment_plan_id" int NOT NULL,
  "sequence" int NOT NULL,
  "due_date" date NOT NULL,
  "amount" decimal(14,2) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'POSTED', 'PAID', 'CANCELED')),
  "transaction_id" int,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("installment_plan_id", "sequence")
);

CREATE INDEX "idx_installment_plans_payment_method" ON "installment_plans" ("payment_method_id");
CREATE INDEX "idx_installment_plans_account" ON "installment_plans" ("account_id");
CREATE INDEX "idx_installment_plans_category" ON "installment_plans" ("category_id");
CREATE INDEX "idx_installment_plans_party" ON "installment_plans" ("party_id");
CREATE INDEX "idx_installment_plan_items_plan" ON "installment_plan_items" ("installment_plan_id");

ALTER TABLE "installment_plans" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("payment_method_id");
ALTER TABLE "installment_plans" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("account_id");
ALTER TABLE "installment_plans" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");
ALTER TABLE "installment_plans" ADD FOREIGN KEY ("party_id") REFERENCES "parties" ("party_id");
ALTER TABLE "installment_plan_items" ADD FOREIGN KEY ("installment_plan_id") REFERENCES "installment_plans" ("installment_plan_id") ON DELETE CASCADE;
ALTER TABLE "installment_plan_items" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id");
