CREATE TABLE budget_periods (
  budget_period_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month date NOT NULL UNIQUE,
  analysis_mode varchar(20),
  is_closed boolean NOT NULL DEFAULT false
);

CREATE TABLE budget_items (
  budget_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_period_id int NOT NULL,
  category_id int NOT NULL,
  mode varchar(30) NOT NULL,
  planned_amount decimal(14,2),
  target_percent decimal(5,2),
  notes text,
  UNIQUE (budget_period_id, category_id)
);

ALTER TABLE budget_items
  ADD FOREIGN KEY (budget_period_id) REFERENCES budget_periods (budget_period_id) ON DELETE CASCADE;

ALTER TABLE budget_items
  ADD FOREIGN KEY (category_id) REFERENCES categories (category_id);
