CREATE TABLE "cashflow_entries" (
  "cashflow_entry_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" int NOT NULL,
  "category_id" int NOT NULL,
  "payment_method_id" int NOT NULL,
  "installment_plan_id" int,
  "installment_plan_item_id" int,
  "direction" varchar(3) NOT NULL CHECK (direction IN ('IN', 'OUT')),
  "title" varchar(255) NOT NULL,
  "amount" decimal(14,2) NOT NULL CHECK (amount > 0),
  "is_fixed" boolean NOT NULL DEFAULT false,
  "occurred_at" date NOT NULL,
  "reversal_of_entry_id" int,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX "idx_cashflow_entries_month" ON "cashflow_entries" ("occurred_at");
CREATE INDEX "idx_cashflow_entries_direction" ON "cashflow_entries" ("direction");
CREATE INDEX "idx_cashflow_entries_fixed" ON "cashflow_entries" ("is_fixed");

ALTER TABLE "cashflow_entries" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id") ON DELETE CASCADE;
ALTER TABLE "cashflow_entries" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");
ALTER TABLE "cashflow_entries" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("payment_method_id");
ALTER TABLE "cashflow_entries" ADD FOREIGN KEY ("installment_plan_id") REFERENCES "installment_plans" ("installment_plan_id") ON DELETE SET NULL;
ALTER TABLE "cashflow_entries" ADD FOREIGN KEY ("installment_plan_item_id") REFERENCES "installment_plan_items" ("installment_plan_item_id") ON DELETE SET NULL;
ALTER TABLE "cashflow_entries" ADD FOREIGN KEY ("reversal_of_entry_id") REFERENCES "cashflow_entries" ("cashflow_entry_id");
