CREATE TABLE picuinha_cases (
  picuinha_case_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id int NOT NULL REFERENCES picuinha_persons (person_id),
  title varchar(255) NOT NULL,
  case_type varchar(30) NOT NULL,
  total_amount decimal(14,2),
  installment_count int,
  installment_amount decimal(14,2),
  start_date date NOT NULL,
  payment_method_id int REFERENCES payment_methods (payment_method_id),
  installment_plan_id int REFERENCES installment_plans (installment_plan_id),
  category_id int REFERENCES flow_categories (category_id),
  interest_rate decimal(6,3),
  interest_rate_unit varchar(10),
  recurrence_interval_months int,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX idx_picuinha_cases_person_id ON picuinha_cases (person_id);
CREATE INDEX idx_picuinha_cases_payment_method_id ON picuinha_cases (payment_method_id);

CREATE TABLE picuinha_case_installments (
  picuinha_case_installment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  picuinha_case_id int NOT NULL REFERENCES picuinha_cases (picuinha_case_id) ON DELETE CASCADE,
  installment_number int NOT NULL,
  due_date date NOT NULL,
  amount decimal(14,2) NOT NULL CHECK (amount >= 0),
  extra_amount decimal(14,2) NOT NULL DEFAULT 0,
  is_paid boolean NOT NULL DEFAULT false,
  paid_at timestamp
);

CREATE UNIQUE INDEX idx_picuinha_case_installments_unique ON picuinha_case_installments (picuinha_case_id, installment_number);
CREATE INDEX idx_picuinha_case_installments_due_date ON picuinha_case_installments (due_date);
