ALTER TABLE installment_plans
  RENAME COLUMN start_month TO start_date;

ALTER TABLE installment_plans
  ALTER COLUMN payment_method_id DROP NOT NULL;

ALTER TABLE installment_plans
  ADD COLUMN plan_type varchar(30) NOT NULL DEFAULT 'CARD_INSTALLMENT',
  ADD COLUMN person_id int REFERENCES picuinha_persons (person_id),
  ADD COLUMN category_id int REFERENCES flow_categories (category_id),
  ADD COLUMN interest_rate decimal(6,3),
  ADD COLUMN interest_rate_unit varchar(10),
  ADD COLUMN recurrence_interval_months int,
  ADD COLUMN created_at timestamp NOT NULL DEFAULT now();

CREATE TABLE installment_plan_items (
  installment_plan_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installment_plan_id int NOT NULL REFERENCES installment_plans (installment_plan_id) ON DELETE CASCADE,
  installment_number int NOT NULL,
  due_date date NOT NULL,
  amount decimal(14,2) NOT NULL CHECK (amount >= 0),
  extra_amount decimal(14,2) NOT NULL DEFAULT 0,
  is_paid boolean NOT NULL DEFAULT false,
  paid_at timestamp,
  cash_flow_id int REFERENCES cash_flows (cash_flow_id)
);

CREATE UNIQUE INDEX idx_installment_plan_items_unique ON installment_plan_items (installment_plan_id, installment_number);
CREATE INDEX idx_installment_plan_items_due_date ON installment_plan_items (due_date);

DROP TABLE IF EXISTS picuinha_case_installments;
DROP TABLE IF EXISTS picuinha_cases;
