// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package categories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (ledger_id, parent_id, name, direction, is_budget_base, is_budget_relevant, is_active, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ledger_id, parent_id, name, direction, is_budget_base, is_budget_relevant, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	LedgerID         pgtype.UUID
	ParentID         pgtype.UUID
	Name             string
	Direction        string
	IsBudgetBase     bool
	IsBudgetRelevant bool
	IsActive         bool
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.LedgerID,
		arg.ParentID,
		arg.Name,
		arg.Direction,
		arg.IsBudgetBase,
		arg.IsBudgetRelevant,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.ParentID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetBase,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :one
UPDATE categories
SET is_active = false, updated_at = $3
WHERE ledger_id = $1 AND id = $2
RETURNING id, ledger_id, parent_id, name, direction, is_budget_base, is_budget_relevant, is_active, created_at, updated_at
`

type DeactivateCategoryParams struct {
	LedgerID  pgtype.UUID
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) DeactivateCategory(ctx context.Context, arg DeactivateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, deactivateCategory, arg.LedgerID, arg.ID, arg.UpdatedAt)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.ParentID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetBase,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCategoryByName = `-- name: FindCategoryByName :one
SELECT id
FROM categories
WHERE ledger_id = $1 AND name = $2
LIMIT 1
`

type FindCategoryByNameParams struct {
	LedgerID pgtype.UUID
	Name     string
}

func (q *Queries) FindCategoryByName(ctx context.Context, arg FindCategoryByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCategoryByName, arg.LedgerID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCategoryBudgetInfo = `-- name: GetCategoryBudgetInfo :one
SELECT direction, is_budget_relevant
FROM categories
WHERE ledger_id = $1 AND id = $2
`

type GetCategoryBudgetInfoParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

type GetCategoryBudgetInfoRow struct {
	Direction        string
	IsBudgetRelevant bool
}

func (q *Queries) GetCategoryBudgetInfo(ctx context.Context, arg GetCategoryBudgetInfoParams) (GetCategoryBudgetInfoRow, error) {
	row := q.db.QueryRow(ctx, getCategoryBudgetInfo, arg.LedgerID, arg.ID)
	var i GetCategoryBudgetInfoRow
	err := row.Scan(&i.Direction, &i.IsBudgetRelevant)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, ledger_id, parent_id, name, direction, is_budget_base, is_budget_relevant, is_active, created_at, updated_at
FROM categories
WHERE ledger_id = $1 AND id = $2
`

type GetCategoryByIDParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.LedgerID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.ParentID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetBase,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryDirection = `-- name: GetCategoryDirection :one
SELECT direction
FROM categories
WHERE ledger_id = $1 AND id = $2
`

type GetCategoryDirectionParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetCategoryDirection(ctx context.Context, arg GetCategoryDirectionParams) (string, error) {
	row := q.db.QueryRow(ctx, getCategoryDirection, arg.LedgerID, arg.ID)
	var direction string
	err := row.Scan(&direction)
	return direction, err
}

const listCategoriesByLedger = `-- name: ListCategoriesByLedger :many

SELECT id, ledger_id, parent_id, name, direction, is_budget_base, is_budget_relevant, is_active, created_at, updated_at
FROM categories
WHERE ledger_id = $1
  AND ($2::text IS NULL OR direction = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY name
`

type ListCategoriesByLedgerParams struct {
	LedgerID pgtype.UUID
	Column2  string
	Column3  bool
}

// Categories
func (q *Queries) ListCategoriesByLedger(ctx context.Context, arg ListCategoriesByLedgerParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByLedger, arg.LedgerID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.ParentID,
			&i.Name,
			&i.Direction,
			&i.IsBudgetBase,
			&i.IsBudgetRelevant,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryDescendants = `-- name: ListCategoryDescendants :many
WITH RECURSIVE tree AS (
  SELECT categories.id, categories.parent_id
  FROM categories
  WHERE categories.ledger_id = $1 AND categories.id = $2
  UNION ALL
  SELECT c.id, c.parent_id
  FROM categories c
  JOIN tree t ON t.id = c.parent_id
  WHERE c.ledger_id = $1
)
SELECT tree.id
FROM tree
`

type ListCategoryDescendantsParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) ListCategoryDescendants(ctx context.Context, arg ListCategoryDescendantsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCategoryDescendants, arg.LedgerID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET parent_id = $3, name = $4, direction = $5, is_budget_base = $6, is_budget_relevant = $7, is_active = $8, updated_at = $9
WHERE ledger_id = $1 AND id = $2
RETURNING id, ledger_id, parent_id, name, direction, is_budget_base, is_budget_relevant, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	LedgerID         pgtype.UUID
	ID               pgtype.UUID
	ParentID         pgtype.UUID
	Name             string
	Direction        string
	IsBudgetBase     bool
	IsBudgetRelevant bool
	IsActive         bool
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.LedgerID,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Direction,
		arg.IsBudgetBase,
		arg.IsBudgetRelevant,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.ParentID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetBase,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
