// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package journal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTransactionReferences = `-- name: CheckTransactionReferences :one
SELECT
  EXISTS (SELECT 1 FROM installments WHERE posted_transaction_id = $1) AS has_installment_post,
  EXISTS (SELECT 1 FROM credit_card_statements WHERE payment_transaction_id = $1) AS has_statement_payment
`

type CheckTransactionReferencesRow struct {
	HasInstallmentPost  bool
	HasStatementPayment bool
}

func (q *Queries) CheckTransactionReferences(ctx context.Context, postedTransactionID pgtype.UUID) (CheckTransactionReferencesRow, error) {
	row := q.db.QueryRow(ctx, checkTransactionReferences, postedTransactionID)
	var i CheckTransactionReferencesRow
	err := row.Scan(&i.HasInstallmentPost, &i.HasStatementPayment)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (ledger_id, transaction_id, account_id, category_id, kind, amount_cents, memo, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ledger_id, transaction_id, account_id, category_id, kind, amount_cents, memo, created_at, updated_at
`

type CreateEntryParams struct {
	LedgerID      pgtype.UUID
	TransactionID pgtype.UUID
	AccountID     pgtype.UUID
	CategoryID    pgtype.UUID
	Kind          string
	AmountCents   int64
	Memo          pgtype.Text
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.LedgerID,
		arg.TransactionID,
		arg.AccountID,
		arg.CategoryID,
		arg.Kind,
		arg.AmountCents,
		arg.Memo,
		arg.UpdatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.TransactionID,
		&i.AccountID,
		&i.CategoryID,
		&i.Kind,
		&i.AmountCents,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (ledger_id, occurred_at, description, notes, created_by_user_id, credit_card_id, investment_action, external_source, external_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, ledger_id, occurred_at, description, notes, created_by_user_id, credit_card_id, investment_action, created_at, updated_at
`

type CreateTransactionParams struct {
	LedgerID         pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	Description      string
	Notes            pgtype.Text
	CreatedByUserID  pgtype.UUID
	CreditCardID     pgtype.UUID
	InvestmentAction pgtype.Text
	ExternalSource   pgtype.Text
	ExternalID       pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

type CreateTransactionRow struct {
	ID               pgtype.UUID
	LedgerID         pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	Description      string
	Notes            pgtype.Text
	CreatedByUserID  pgtype.UUID
	CreditCardID     pgtype.UUID
	InvestmentAction pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Journal: transactions + entries
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.LedgerID,
		arg.OccurredAt,
		arg.Description,
		arg.Notes,
		arg.CreatedByUserID,
		arg.CreditCardID,
		arg.InvestmentAction,
		arg.ExternalSource,
		arg.ExternalID,
		arg.UpdatedAt,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.OccurredAt,
		&i.Description,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CreditCardID,
		&i.InvestmentAction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntriesByTransaction = `-- name: DeleteEntriesByTransaction :exec
DELETE FROM entries
WHERE ledger_id = $1 AND transaction_id = $2
`

type DeleteEntriesByTransactionParams struct {
	LedgerID      pgtype.UUID
	TransactionID pgtype.UUID
}

func (q *Queries) DeleteEntriesByTransaction(ctx context.Context, arg DeleteEntriesByTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteEntriesByTransaction, arg.LedgerID, arg.TransactionID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE ledger_id = $1 AND id = $2
`

type DeleteTransactionParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.LedgerID, arg.ID)
	return err
}

const getTransactionByExternal = `-- name: GetTransactionByExternal :one
SELECT id, ledger_id, occurred_at, description, notes, created_by_user_id, credit_card_id, investment_action, external_source, external_id, created_at, updated_at
FROM transactions
WHERE ledger_id = $1 AND external_source = $2 AND external_id = $3
`

type GetTransactionByExternalParams struct {
	LedgerID       pgtype.UUID
	ExternalSource pgtype.Text
	ExternalID     pgtype.Text
}

type GetTransactionByExternalRow struct {
	ID               pgtype.UUID
	LedgerID         pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	Description      string
	Notes            pgtype.Text
	CreatedByUserID  pgtype.UUID
	CreditCardID     pgtype.UUID
	InvestmentAction pgtype.Text
	ExternalSource   pgtype.Text
	ExternalID       pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetTransactionByExternal(ctx context.Context, arg GetTransactionByExternalParams) (GetTransactionByExternalRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByExternal, arg.LedgerID, arg.ExternalSource, arg.ExternalID)
	var i GetTransactionByExternalRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.OccurredAt,
		&i.Description,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CreditCardID,
		&i.InvestmentAction,
		&i.ExternalSource,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionWithEntries = `-- name: GetTransactionWithEntries :many
SELECT t.id, t.ledger_id, t.occurred_at, t.description, t.notes, t.created_by_user_id, t.credit_card_id, t.investment_action, t.created_at, t.updated_at,
  e.id, e.ledger_id, e.transaction_id, e.account_id, e.category_id, e.kind, e.amount_cents, e.memo, e.created_at, e.updated_at
FROM transactions t
JOIN entries e ON e.transaction_id = t.id
WHERE t.ledger_id = $1 AND t.id = $2
ORDER BY e.created_at ASC
`

type GetTransactionWithEntriesParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

type GetTransactionWithEntriesRow struct {
	ID               pgtype.UUID
	LedgerID         pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	Description      string
	Notes            pgtype.Text
	CreatedByUserID  pgtype.UUID
	CreditCardID     pgtype.UUID
	InvestmentAction pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ID_2             pgtype.UUID
	LedgerID_2       pgtype.UUID
	TransactionID    pgtype.UUID
	AccountID        pgtype.UUID
	CategoryID       pgtype.UUID
	Kind             string
	AmountCents      int64
	Memo             pgtype.Text
	CreatedAt_2      pgtype.Timestamptz
	UpdatedAt_2      pgtype.Timestamptz
}

func (q *Queries) GetTransactionWithEntries(ctx context.Context, arg GetTransactionWithEntriesParams) ([]GetTransactionWithEntriesRow, error) {
	rows, err := q.db.Query(ctx, getTransactionWithEntries, arg.LedgerID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionWithEntriesRow
	for rows.Next() {
		var i GetTransactionWithEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.OccurredAt,
			&i.Description,
			&i.Notes,
			&i.CreatedByUserID,
			&i.CreditCardID,
			&i.InvestmentAction,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.LedgerID_2,
			&i.TransactionID,
			&i.AccountID,
			&i.CategoryID,
			&i.Kind,
			&i.AmountCents,
			&i.Memo,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByTransaction = `-- name: ListEntriesByTransaction :many
SELECT id, ledger_id, transaction_id, account_id, category_id, kind, amount_cents, memo, created_at, updated_at
FROM entries
WHERE ledger_id = $1 AND transaction_id = $2
ORDER BY created_at ASC
`

type ListEntriesByTransactionParams struct {
	LedgerID      pgtype.UUID
	TransactionID pgtype.UUID
}

func (q *Queries) ListEntriesByTransaction(ctx context.Context, arg ListEntriesByTransactionParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByTransaction, arg.LedgerID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.TransactionID,
			&i.AccountID,
			&i.CategoryID,
			&i.Kind,
			&i.AmountCents,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionIDs = `-- name: ListTransactionIDs :many
SELECT t.id, t.occurred_at
FROM transactions t
WHERE t.ledger_id = $1
  AND ($2::timestamptz IS NULL OR t.occurred_at >= $2)
  AND ($3::timestamptz IS NULL OR t.occurred_at <= $3)
  AND ($4::uuid IS NULL OR EXISTS (
    SELECT 1 FROM entries e
    WHERE e.transaction_id = t.id AND e.account_id = $4
  ))
  AND ($5::uuid IS NULL OR EXISTS (
    SELECT 1 FROM entries e
    WHERE e.transaction_id = t.id AND e.category_id = $5
  ))
  AND ($6::text IS NULL OR (t.description ILIKE $6 OR t.notes ILIKE $6))
  AND ($7::timestamptz IS NULL OR (t.occurred_at < $7 OR (t.occurred_at = $7 AND t.id < $8)))
ORDER BY t.occurred_at DESC, t.id DESC
LIMIT $9
`

type ListTransactionIDsParams struct {
	LedgerID pgtype.UUID
	Column2  pgtype.Timestamptz
	Column3  pgtype.Timestamptz
	Column4  pgtype.UUID
	Column5  pgtype.UUID
	Column6  string
	Column7  pgtype.Timestamptz
	ID       pgtype.UUID
	Limit    int32
}

type ListTransactionIDsRow struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) ListTransactionIDs(ctx context.Context, arg ListTransactionIDsParams) ([]ListTransactionIDsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionIDs,
		arg.LedgerID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionIDsRow
	for rows.Next() {
		var i ListTransactionIDsRow
		if err := rows.Scan(&i.ID, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithEntries = `-- name: ListTransactionsWithEntries :many
SELECT t.id, t.ledger_id, t.occurred_at, t.description, t.notes, t.created_by_user_id, t.credit_card_id, t.investment_action, t.created_at, t.updated_at,
  e.id, e.ledger_id, e.transaction_id, e.account_id, e.category_id, e.kind, e.amount_cents, e.memo, e.created_at, e.updated_at
FROM transactions t
JOIN entries e ON e.transaction_id = t.id
WHERE t.id = ANY($1::uuid[])
ORDER BY t.occurred_at DESC, t.id DESC, e.created_at ASC
`

type ListTransactionsWithEntriesRow struct {
	ID               pgtype.UUID
	LedgerID         pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	Description      string
	Notes            pgtype.Text
	CreatedByUserID  pgtype.UUID
	CreditCardID     pgtype.UUID
	InvestmentAction pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ID_2             pgtype.UUID
	LedgerID_2       pgtype.UUID
	TransactionID    pgtype.UUID
	AccountID        pgtype.UUID
	CategoryID       pgtype.UUID
	Kind             string
	AmountCents      int64
	Memo             pgtype.Text
	CreatedAt_2      pgtype.Timestamptz
	UpdatedAt_2      pgtype.Timestamptz
}

func (q *Queries) ListTransactionsWithEntries(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTransactionsWithEntriesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsWithEntries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsWithEntriesRow
	for rows.Next() {
		var i ListTransactionsWithEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.OccurredAt,
			&i.Description,
			&i.Notes,
			&i.CreatedByUserID,
			&i.CreditCardID,
			&i.InvestmentAction,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.LedgerID_2,
			&i.TransactionID,
			&i.AccountID,
			&i.CategoryID,
			&i.Kind,
			&i.AmountCents,
			&i.Memo,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET occurred_at = $3, description = $4, notes = $5, updated_at = $6
WHERE ledger_id = $1 AND id = $2
RETURNING id, ledger_id, occurred_at, description, notes, created_by_user_id, credit_card_id, investment_action, created_at, updated_at
`

type UpdateTransactionParams struct {
	LedgerID    pgtype.UUID
	ID          pgtype.UUID
	OccurredAt  pgtype.Timestamptz
	Description string
	Notes       pgtype.Text
	UpdatedAt   pgtype.Timestamptz
}

type UpdateTransactionRow struct {
	ID               pgtype.UUID
	LedgerID         pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	Description      string
	Notes            pgtype.Text
	CreatedByUserID  pgtype.UUID
	CreditCardID     pgtype.UUID
	InvestmentAction pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.LedgerID,
		arg.ID,
		arg.OccurredAt,
		arg.Description,
		arg.Notes,
		arg.UpdatedAt,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.OccurredAt,
		&i.Description,
		&i.Notes,
		&i.CreatedByUserID,
		&i.CreditCardID,
		&i.InvestmentAction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
