// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investments.sql

package investments

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAccountByType = `-- name: FindAccountByType :one

SELECT id
FROM accounts
WHERE ledger_id = $1 AND type = $2 AND is_active = true
ORDER BY created_at ASC
LIMIT 1
`

type FindAccountByTypeParams struct {
	LedgerID pgtype.UUID
	Type     string
}

// Investments support queries
func (q *Queries) FindAccountByType(ctx context.Context, arg FindAccountByTypeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAccountByType, arg.LedgerID, arg.Type)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findCategoryByName = `-- name: FindCategoryByName :one
SELECT id
FROM categories
WHERE ledger_id = $1 AND name = $2
LIMIT 1
`

type FindCategoryByNameParams struct {
	LedgerID pgtype.UUID
	Name     string
}

func (q *Queries) FindCategoryByName(ctx context.Context, arg FindCategoryByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCategoryByName, arg.LedgerID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCategoryDirection = `-- name: GetCategoryDirection :one
SELECT direction
FROM categories
WHERE ledger_id = $1 AND id = $2
`

type GetCategoryDirectionParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetCategoryDirection(ctx context.Context, arg GetCategoryDirectionParams) (string, error) {
	row := q.db.QueryRow(ctx, getCategoryDirection, arg.LedgerID, arg.ID)
	var direction string
	err := row.Scan(&direction)
	return direction, err
}

const sumByCategory = `-- name: SumByCategory :one
SELECT COALESCE(SUM(e.amount_cents), 0)
FROM entries e
JOIN transactions t ON t.id = e.transaction_id
WHERE e.ledger_id = $1
  AND e.category_id = $2
  AND t.occurred_at >= $3 AND t.occurred_at <= $4
`

type SumByCategoryParams struct {
	LedgerID     pgtype.UUID
	CategoryID   pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	OccurredAt_2 pgtype.Timestamptz
}

func (q *Queries) SumByCategory(ctx context.Context, arg SumByCategoryParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumByCategory,
		arg.LedgerID,
		arg.CategoryID,
		arg.OccurredAt,
		arg.OccurredAt_2,
	)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
