// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash_flows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCashFlow = `-- name: CreateCashFlow :one
INSERT INTO cash_flows (
  date,
  category_id,
  direction,
  title,
  amount
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING cash_flow_id, date, category_id, direction, title, amount
`

type CreateCashFlowParams struct {
	Date       pgtype.Date
	CategoryID int32
	Direction  string
	Title      string
	Amount     pgtype.Numeric
}

func (q *Queries) CreateCashFlow(ctx context.Context, arg CreateCashFlowParams) (CashFlow, error) {
	row := q.db.QueryRow(ctx, createCashFlow,
		arg.Date,
		arg.CategoryID,
		arg.Direction,
		arg.Title,
		arg.Amount,
	)
	var i CashFlow
	err := row.Scan(
		&i.CashFlowID,
		&i.Date,
		&i.CategoryID,
		&i.Direction,
		&i.Title,
		&i.Amount,
	)
	return i, err
}

const listCashFlowsByMonth = `-- name: ListCashFlowsByMonth :many
SELECT
  cf.cash_flow_id,
  cf.date,
  cf.category_id,
  cf.direction,
  cf.title,
  cf.amount,
  fc.name AS category_name
FROM cash_flows cf
JOIN flow_categories fc ON fc.category_id = cf.category_id
WHERE date_trunc('month', cf.date) = date_trunc('month', $1::date)
ORDER BY cf.date, cf.cash_flow_id
`

type ListCashFlowsByMonthRow struct {
	CashFlowID   int32
	Date         pgtype.Date
	CategoryID   int32
	Direction    string
	Title        string
	Amount       pgtype.Numeric
	CategoryName string
}

func (q *Queries) ListCashFlowsByMonth(ctx context.Context, dollar_1 pgtype.Date) ([]ListCashFlowsByMonthRow, error) {
	rows, err := q.db.Query(ctx, listCashFlowsByMonth, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCashFlowsByMonthRow
	for rows.Next() {
		var i ListCashFlowsByMonthRow
		if err := rows.Scan(
			&i.CashFlowID,
			&i.Date,
			&i.CategoryID,
			&i.Direction,
			&i.Title,
			&i.Amount,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
