// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO flow_categories (
  name,
  direction,
  is_budget_relevant,
  is_active
) VALUES (
  $1, $2, $3, $4
)
RETURNING category_id, name, direction, is_budget_relevant, is_active
`

type CreateCategoryParams struct {
	Name             string
	Direction        string
	IsBudgetRelevant bool
	IsActive         bool
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (FlowCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Direction,
		arg.IsBudgetRelevant,
		arg.IsActive,
	)
	var i FlowCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT category_id, name, direction, is_budget_relevant, is_active
FROM flow_categories
WHERE category_id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, categoryID int32) (FlowCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, categoryID)
	var i FlowCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, name, direction, is_budget_relevant, is_active
FROM flow_categories
WHERE ($1::boolean = false OR is_active = true)
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, dollar_1 bool) ([]FlowCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowCategory
	for rows.Next() {
		var i FlowCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Direction,
			&i.IsBudgetRelevant,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE flow_categories
SET name = $2,
    direction = $3,
    is_budget_relevant = $4,
    is_active = $5
WHERE category_id = $1
RETURNING category_id, name, direction, is_budget_relevant, is_active
`

type UpdateCategoryParams struct {
	CategoryID       int32
	Name             string
	Direction        string
	IsBudgetRelevant bool
	IsActive         bool
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (FlowCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.CategoryID,
		arg.Name,
		arg.Direction,
		arg.IsBudgetRelevant,
		arg.IsActive,
	)
	var i FlowCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
	)
	return i, err
}
