// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseDetail = `-- name: CreateExpenseDetail :exec
INSERT INTO expense_details (cash_flow_id, payment_method_id, is_fixed, is_future, installment_plan_id, affects_card_invoice)
VALUES ($1, $2, false, true, $3, $4)
`

type CreateExpenseDetailParams struct {
	CashFlowID         int32
	PaymentMethodID    pgtype.Int4
	InstallmentPlanID  pgtype.Int4
	AffectsCardInvoice bool
}

func (q *Queries) CreateExpenseDetail(ctx context.Context, arg CreateExpenseDetailParams) error {
	_, err := q.db.Exec(ctx, createExpenseDetail,
		arg.CashFlowID,
		arg.PaymentMethodID,
		arg.InstallmentPlanID,
		arg.AffectsCardInvoice,
	)
	return err
}

const createInstallmentPlan = `-- name: CreateInstallmentPlan :one
INSERT INTO installment_plans (description, total_amount, installment_count, installment_amount, start_month, payment_method_id, starts_on_current_invoice)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING installment_plan_id, description, total_amount, installment_count, installment_amount, start_month, payment_method_id, starts_on_current_invoice
`

type CreateInstallmentPlanParams struct {
	Description            string
	TotalAmount            pgtype.Numeric
	InstallmentCount       int32
	InstallmentAmount      pgtype.Numeric
	StartMonth             pgtype.Date
	PaymentMethodID        int32
	StartsOnCurrentInvoice bool
}

func (q *Queries) CreateInstallmentPlan(ctx context.Context, arg CreateInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, createInstallmentPlan,
		arg.Description,
		arg.TotalAmount,
		arg.InstallmentCount,
		arg.InstallmentAmount,
		arg.StartMonth,
		arg.PaymentMethodID,
		arg.StartsOnCurrentInvoice,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.InstallmentPlanID,
		&i.Description,
		&i.TotalAmount,
		&i.InstallmentCount,
		&i.InstallmentAmount,
		&i.StartMonth,
		&i.PaymentMethodID,
		&i.StartsOnCurrentInvoice,
	)
	return i, err
}
