// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetItem struct {
	BudgetItemID   int32
	BudgetPeriodID int32
	CategoryID     int32
	Mode           string
	PlannedAmount  pgtype.Numeric
	TargetPercent  pgtype.Numeric
	Notes          pgtype.Text
}

type BudgetPeriod struct {
	BudgetPeriodID int32
	Month          pgtype.Date
	AnalysisMode   pgtype.Text
	IsClosed       bool
}

// Para casos 1,2 e 3 (entradas), você preenche apenas: date, category_id (Ganho/Investimento), title, amount.
type CashFlow struct {
	CashFlowID int32
	Date       pgtype.Date
	CategoryID int32
	Direction  string
	Title      string
	Amount     pgtype.Numeric
	IsFixed    bool
}

// Entradas (Ganhos/Investimentos) NÃO precisam de registro aqui. Apenas saídas mais complexas.
type ExpenseDetail struct {
	ExpenseDetailID    int32
	CashFlowID         int32
	PaymentMethodID    pgtype.Int4
	IsFixed            bool
	IsFuture           bool
	InstallmentPlanID  pgtype.Int4
	AffectsCardInvoice bool
}

// Categorias de ENTRADA (ex.: Ganho, Investimento) e de SAÍDA (ex.: Custos Fixos, Prazeres, Veículo/Transporte etc.)
type FlowCategory struct {
	CategoryID       int32
	Name             string
	Direction        string
	IsBudgetRelevant bool
	IsActive         bool
}

// As parcelas individuais serão representadas por vários cash_flows (SAÍDAS), cada um amarrado ao installment_plan via expense_details.
type InstallmentPlan struct {
	InstallmentPlanID      int32
	Description            string
	TotalAmount            pgtype.Numeric
	InstallmentCount       int32
	InstallmentAmount      pgtype.Numeric
	StartMonth             pgtype.Date
	PaymentMethodID        int32
	StartsOnCurrentInvoice bool
}

type PaymentMethod struct {
	PaymentMethodID int32
	Name            string
	Kind            string
	BankName        pgtype.Text
	ClosingDay      pgtype.Int4
	DueDay          pgtype.Int4
	IsActive        bool
}

// Você terá o saldo por pessoa somando/subtraindo os amounts conforme o kind. O cash_flow_id conecta com o fluxo real (entradas/saídas).
type PicuinhaEntry struct {
	PicuinhaEntryID int32
	PersonID        int32
	Date            pgtype.Date
	Kind            string
	Amount          pgtype.Numeric
	CashFlowID      pgtype.Int4
}

type PicuinhaPerson struct {
	PersonID int32
	Name     string
	Notes    pgtype.Text
}
