// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (name, kind, bank_name, closing_day, due_day, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING payment_method_id, name, kind, bank_name, closing_day, due_day, is_active
`

type CreatePaymentMethodParams struct {
	Name       string
	Kind       string
	BankName   pgtype.Text
	ClosingDay pgtype.Int4
	DueDay     pgtype.Int4
	IsActive   bool
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.Name,
		arg.Kind,
		arg.BankName,
		arg.ClosingDay,
		arg.DueDay,
		arg.IsActive,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.PaymentMethodID,
		&i.Name,
		&i.Kind,
		&i.BankName,
		&i.ClosingDay,
		&i.DueDay,
		&i.IsActive,
	)
	return i, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT payment_method_id, name, kind, bank_name, closing_day, due_day, is_active
FROM payment_methods
WHERE payment_method_id = $1
`

func (q *Queries) GetPaymentMethod(ctx context.Context, paymentMethodID int32) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, paymentMethodID)
	var i PaymentMethod
	err := row.Scan(
		&i.PaymentMethodID,
		&i.Name,
		&i.Kind,
		&i.BankName,
		&i.ClosingDay,
		&i.DueDay,
		&i.IsActive,
	)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT payment_method_id, name, kind, bank_name, closing_day, due_day, is_active
FROM payment_methods
WHERE ($1::boolean IS NULL OR is_active = $1)
ORDER BY name
`

func (q *Queries) ListPaymentMethods(ctx context.Context, isActive pgtype.Bool) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.Name,
			&i.Kind,
			&i.BankName,
			&i.ClosingDay,
			&i.DueDay,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
