// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: picuinhas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO picuinha_persons (name, notes)
VALUES ($1, $2)
RETURNING person_id, name, notes
`

type CreatePersonParams struct {
	Name  string
	Notes pgtype.Text
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (PicuinhaPerson, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.Name, arg.Notes)
	var i PicuinhaPerson
	err := row.Scan(&i.PersonID, &i.Name, &i.Notes)
	return i, err
}

const createPicuinhaEntry = `-- name: CreatePicuinhaEntry :one
INSERT INTO picuinha_entries (person_id, date, kind, amount, cash_flow_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING picuinha_entry_id, person_id, date, kind, amount, cash_flow_id
`

type CreatePicuinhaEntryParams struct {
	PersonID   int32
	Date       pgtype.Date
	Kind       string
	Amount     pgtype.Numeric
	CashFlowID pgtype.Int4
}

func (q *Queries) CreatePicuinhaEntry(ctx context.Context, arg CreatePicuinhaEntryParams) (PicuinhaEntry, error) {
	row := q.db.QueryRow(ctx, createPicuinhaEntry,
		arg.PersonID,
		arg.Date,
		arg.Kind,
		arg.Amount,
		arg.CashFlowID,
	)
	var i PicuinhaEntry
	err := row.Scan(
		&i.PicuinhaEntryID,
		&i.PersonID,
		&i.Date,
		&i.Kind,
		&i.Amount,
		&i.CashFlowID,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT person_id, name, notes
FROM picuinha_persons
WHERE person_id = $1
`

func (q *Queries) GetPerson(ctx context.Context, personID int32) (PicuinhaPerson, error) {
	row := q.db.QueryRow(ctx, getPerson, personID)
	var i PicuinhaPerson
	err := row.Scan(&i.PersonID, &i.Name, &i.Notes)
	return i, err
}

const getPersonBalance = `-- name: GetPersonBalance :one
SELECT COALESCE(SUM(CASE WHEN kind = 'PLUS' THEN amount ELSE -amount END), 0)::decimal
FROM picuinha_entries
WHERE person_id = $1
`

func (q *Queries) GetPersonBalance(ctx context.Context, personID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getPersonBalance, personID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const listEntriesByPerson = `-- name: ListEntriesByPerson :many
SELECT picuinha_entry_id, person_id, date, kind, amount, cash_flow_id
FROM picuinha_entries
WHERE person_id = $1
ORDER BY date DESC
`

func (q *Queries) ListEntriesByPerson(ctx context.Context, personID int32) ([]PicuinhaEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PicuinhaEntry
	for rows.Next() {
		var i PicuinhaEntry
		if err := rows.Scan(
			&i.PicuinhaEntryID,
			&i.PersonID,
			&i.Date,
			&i.Kind,
			&i.Amount,
			&i.CashFlowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersons = `-- name: ListPersons :many
SELECT person_id, name, notes
FROM picuinha_persons
ORDER BY name
`

func (q *Queries) ListPersons(ctx context.Context) ([]PicuinhaPerson, error) {
	rows, err := q.db.Query(ctx, listPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PicuinhaPerson
	for rows.Next() {
		var i PicuinhaPerson
		if err := rows.Scan(&i.PersonID, &i.Name, &i.Notes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
