// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creditcard.sql

package creditcard

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCardNetwork = `-- name: CreateCardNetwork :one
INSERT INTO card_networks (code, display_name)
VALUES ($1, $2)
RETURNING code, display_name, created_at, updated_at
`

type CreateCardNetworkParams struct {
	Code        string
	DisplayName string
}

func (q *Queries) CreateCardNetwork(ctx context.Context, arg CreateCardNetworkParams) (CardNetwork, error) {
	row := q.db.QueryRow(ctx, createCardNetwork, arg.Code, arg.DisplayName)
	var i CardNetwork
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditCard = `-- name: CreateCreditCard :one
INSERT INTO credit_cards (account_id, issuer_name, network, nickname, last4, credit_limit_cents, closing_day, due_day)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING account_id, issuer_name, network, nickname, last4, credit_limit_cents, closing_day, due_day, created_at, updated_at
`

type CreateCreditCardParams struct {
	AccountID        pgtype.UUID
	IssuerName       pgtype.Text
	Network          string
	Nickname         pgtype.Text
	Last4            pgtype.Text
	CreditLimitCents pgtype.Int8
	ClosingDay       int32
	DueDay           int32
}

func (q *Queries) CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, createCreditCard,
		arg.AccountID,
		arg.IssuerName,
		arg.Network,
		arg.Nickname,
		arg.Last4,
		arg.CreditLimitCents,
		arg.ClosingDay,
		arg.DueDay,
	)
	var i CreditCard
	err := row.Scan(
		&i.AccountID,
		&i.IssuerName,
		&i.Network,
		&i.Nickname,
		&i.Last4,
		&i.CreditLimitCents,
		&i.ClosingDay,
		&i.DueDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallment = `-- name: CreateInstallment :exec
INSERT INTO installments (ledger_id, plan_id, installment_no, due_month, amount_cents, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInstallmentParams struct {
	LedgerID      pgtype.UUID
	PlanID        pgtype.UUID
	InstallmentNo int32
	DueMonth      pgtype.Date
	AmountCents   int64
	Status        string
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) error {
	_, err := q.db.Exec(ctx, createInstallment,
		arg.LedgerID,
		arg.PlanID,
		arg.InstallmentNo,
		arg.DueMonth,
		arg.AmountCents,
		arg.Status,
	)
	return err
}

const createInstallmentPlan = `-- name: CreateInstallmentPlan :one

INSERT INTO installment_plans (ledger_id, card_account_id, purchase_occurred_at, merchant, description, category_id, total_amount_cents, installments_count, installment_amount_cents, first_due_month, status, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, ledger_id, card_account_id, purchase_occurred_at, merchant, description, category_id, total_amount_cents, installments_count, installment_amount_cents, first_due_month, status, created_by_user_id, created_at, updated_at
`

type CreateInstallmentPlanParams struct {
	LedgerID               pgtype.UUID
	CardAccountID          pgtype.UUID
	PurchaseOccurredAt     pgtype.Timestamptz
	Merchant               pgtype.Text
	Description            string
	CategoryID             pgtype.UUID
	TotalAmountCents       int64
	InstallmentsCount      int32
	InstallmentAmountCents int64
	FirstDueMonth          pgtype.Date
	Status                 string
	CreatedByUserID        pgtype.UUID
}

// Installment plans
func (q *Queries) CreateInstallmentPlan(ctx context.Context, arg CreateInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, createInstallmentPlan,
		arg.LedgerID,
		arg.CardAccountID,
		arg.PurchaseOccurredAt,
		arg.Merchant,
		arg.Description,
		arg.CategoryID,
		arg.TotalAmountCents,
		arg.InstallmentsCount,
		arg.InstallmentAmountCents,
		arg.FirstDueMonth,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.PurchaseOccurredAt,
		&i.Merchant,
		&i.Description,
		&i.CategoryID,
		&i.TotalAmountCents,
		&i.InstallmentsCount,
		&i.InstallmentAmountCents,
		&i.FirstDueMonth,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStatement = `-- name: CreateStatement :one
INSERT INTO credit_card_statements (ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id, created_at, updated_at
`

type CreateStatementParams struct {
	LedgerID             pgtype.UUID
	CardAccountID        pgtype.UUID
	StatementMonth       pgtype.Date
	ClosingDate          pgtype.Date
	DueDate              pgtype.Date
	TotalChargesCents    int64
	TotalPaymentsCents   int64
	Status               string
	PaymentTransactionID pgtype.UUID
}

func (q *Queries) CreateStatement(ctx context.Context, arg CreateStatementParams) (CreditCardStatement, error) {
	row := q.db.QueryRow(ctx, createStatement,
		arg.LedgerID,
		arg.CardAccountID,
		arg.StatementMonth,
		arg.ClosingDate,
		arg.DueDate,
		arg.TotalChargesCents,
		arg.TotalPaymentsCents,
		arg.Status,
		arg.PaymentTransactionID,
	)
	var i CreditCardStatement
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.StatementMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalChargesCents,
		&i.TotalPaymentsCents,
		&i.Status,
		&i.PaymentTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCardNetwork = `-- name: DeleteCardNetwork :exec
DELETE FROM card_networks
WHERE code = $1
`

func (q *Queries) DeleteCardNetwork(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteCardNetwork, code)
	return err
}

const deleteCreditCard = `-- name: DeleteCreditCard :exec
DELETE FROM credit_cards
WHERE account_id = $1
`

func (q *Queries) DeleteCreditCard(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCreditCard, accountID)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM installment_plans
WHERE ledger_id = $1 AND id = $2
`

type DeletePlanParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) error {
	_, err := q.db.Exec(ctx, deletePlan, arg.LedgerID, arg.ID)
	return err
}

const findCategoryByName = `-- name: FindCategoryByName :one
SELECT id
FROM categories
WHERE ledger_id = $1 AND name = $2
LIMIT 1
`

type FindCategoryByNameParams struct {
	LedgerID pgtype.UUID
	Name     string
}

func (q *Queries) FindCategoryByName(ctx context.Context, arg FindCategoryByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findCategoryByName, arg.LedgerID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountLedger = `-- name: GetAccountLedger :one
SELECT ledger_id
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountLedger(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAccountLedger, id)
	var ledger_id pgtype.UUID
	err := row.Scan(&ledger_id)
	return ledger_id, err
}

const getAccountType = `-- name: GetAccountType :one

SELECT type
FROM accounts
WHERE ledger_id = $1 AND id = $2
`

type GetAccountTypeParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

// Accounts lookup
func (q *Queries) GetAccountType(ctx context.Context, arg GetAccountTypeParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccountType, arg.LedgerID, arg.ID)
	var type_ string
	err := row.Scan(&type_)
	return type_, err
}

const getCardNetwork = `-- name: GetCardNetwork :one
SELECT code, display_name, created_at, updated_at
FROM card_networks
WHERE code = $1
`

func (q *Queries) GetCardNetwork(ctx context.Context, code string) (CardNetwork, error) {
	row := q.db.QueryRow(ctx, getCardNetwork, code)
	var i CardNetwork
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBudgetInfo = `-- name: GetCategoryBudgetInfo :one

SELECT direction, is_budget_relevant
FROM categories
WHERE ledger_id = $1 AND id = $2
`

type GetCategoryBudgetInfoParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

type GetCategoryBudgetInfoRow struct {
	Direction        string
	IsBudgetRelevant bool
}

// Categories lookup
func (q *Queries) GetCategoryBudgetInfo(ctx context.Context, arg GetCategoryBudgetInfoParams) (GetCategoryBudgetInfoRow, error) {
	row := q.db.QueryRow(ctx, getCategoryBudgetInfo, arg.LedgerID, arg.ID)
	var i GetCategoryBudgetInfoRow
	err := row.Scan(&i.Direction, &i.IsBudgetRelevant)
	return i, err
}

const getCreditCard = `-- name: GetCreditCard :one
SELECT c.account_id, a.ledger_id, c.issuer_name, c.network, c.nickname, c.last4, c.credit_limit_cents, c.closing_day, c.due_day, c.created_at, c.updated_at
FROM credit_cards c
JOIN accounts a ON a.id = c.account_id
WHERE a.ledger_id = $1 AND c.account_id = $2
`

type GetCreditCardParams struct {
	LedgerID  pgtype.UUID
	AccountID pgtype.UUID
}

type GetCreditCardRow struct {
	AccountID        pgtype.UUID
	LedgerID         pgtype.UUID
	IssuerName       pgtype.Text
	Network          string
	Nickname         pgtype.Text
	Last4            pgtype.Text
	CreditLimitCents pgtype.Int8
	ClosingDay       int32
	DueDay           int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCreditCard(ctx context.Context, arg GetCreditCardParams) (GetCreditCardRow, error) {
	row := q.db.QueryRow(ctx, getCreditCard, arg.LedgerID, arg.AccountID)
	var i GetCreditCardRow
	err := row.Scan(
		&i.AccountID,
		&i.LedgerID,
		&i.IssuerName,
		&i.Network,
		&i.Nickname,
		&i.Last4,
		&i.CreditLimitCents,
		&i.ClosingDay,
		&i.DueDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, ledger_id, card_account_id, purchase_occurred_at, merchant, description, category_id, total_amount_cents, installments_count, installment_amount_cents, first_due_month, status, created_by_user_id, created_at, updated_at
FROM installment_plans
WHERE ledger_id = $1 AND card_account_id = $2 AND id = $3
`

type GetPlanParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	ID            pgtype.UUID
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, getPlan, arg.LedgerID, arg.CardAccountID, arg.ID)
	var i InstallmentPlan
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.PurchaseOccurredAt,
		&i.Merchant,
		&i.Description,
		&i.CategoryID,
		&i.TotalAmountCents,
		&i.InstallmentsCount,
		&i.InstallmentAmountCents,
		&i.FirstDueMonth,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanCategory = `-- name: GetPlanCategory :one
SELECT category_id
FROM installment_plans
WHERE ledger_id = $1 AND id = $2
`

type GetPlanCategoryParams struct {
	LedgerID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetPlanCategory(ctx context.Context, arg GetPlanCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPlanCategory, arg.LedgerID, arg.ID)
	var category_id pgtype.UUID
	err := row.Scan(&category_id)
	return category_id, err
}

const getStatement = `-- name: GetStatement :one

SELECT id, ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id, created_at, updated_at
FROM credit_card_statements
WHERE ledger_id = $1 AND card_account_id = $2 AND id = $3
`

type GetStatementParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	ID            pgtype.UUID
}

// Statements
func (q *Queries) GetStatement(ctx context.Context, arg GetStatementParams) (CreditCardStatement, error) {
	row := q.db.QueryRow(ctx, getStatement, arg.LedgerID, arg.CardAccountID, arg.ID)
	var i CreditCardStatement
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.StatementMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalChargesCents,
		&i.TotalPaymentsCents,
		&i.Status,
		&i.PaymentTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatementByMonth = `-- name: GetStatementByMonth :one
SELECT id, ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id, created_at, updated_at
FROM credit_card_statements
WHERE ledger_id = $1 AND card_account_id = $2 AND statement_month = $3
`

type GetStatementByMonthParams struct {
	LedgerID       pgtype.UUID
	CardAccountID  pgtype.UUID
	StatementMonth pgtype.Date
}

func (q *Queries) GetStatementByMonth(ctx context.Context, arg GetStatementByMonthParams) (CreditCardStatement, error) {
	row := q.db.QueryRow(ctx, getStatementByMonth, arg.LedgerID, arg.CardAccountID, arg.StatementMonth)
	var i CreditCardStatement
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.StatementMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalChargesCents,
		&i.TotalPaymentsCents,
		&i.Status,
		&i.PaymentTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPostedInstallments = `-- name: HasPostedInstallments :one
SELECT EXISTS (
  SELECT 1
  FROM installments
  WHERE ledger_id = $1 AND plan_id = $2 AND status IN ('posted', 'paid')
) AS exists
`

type HasPostedInstallmentsParams struct {
	LedgerID pgtype.UUID
	PlanID   pgtype.UUID
}

func (q *Queries) HasPostedInstallments(ctx context.Context, arg HasPostedInstallmentsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostedInstallments, arg.LedgerID, arg.PlanID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCardNetworks = `-- name: ListCardNetworks :many

SELECT code, display_name, created_at, updated_at
FROM card_networks
ORDER BY code
`

// Card networks
func (q *Queries) ListCardNetworks(ctx context.Context) ([]CardNetwork, error) {
	rows, err := q.db.Query(ctx, listCardNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardNetwork
	for rows.Next() {
		var i CardNetwork
		if err := rows.Scan(
			&i.Code,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditCards = `-- name: ListCreditCards :many

SELECT c.account_id, a.ledger_id, c.issuer_name, c.network, c.nickname, c.last4, c.credit_limit_cents, c.closing_day, c.due_day, c.created_at, c.updated_at
FROM credit_cards c
JOIN accounts a ON a.id = c.account_id
WHERE a.ledger_id = $1
ORDER BY c.created_at
`

type ListCreditCardsRow struct {
	AccountID        pgtype.UUID
	LedgerID         pgtype.UUID
	IssuerName       pgtype.Text
	Network          string
	Nickname         pgtype.Text
	Last4            pgtype.Text
	CreditLimitCents pgtype.Int8
	ClosingDay       int32
	DueDay           int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Credit cards
func (q *Queries) ListCreditCards(ctx context.Context, ledgerID pgtype.UUID) ([]ListCreditCardsRow, error) {
	rows, err := q.db.Query(ctx, listCreditCards, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreditCardsRow
	for rows.Next() {
		var i ListCreditCardsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.LedgerID,
			&i.IssuerName,
			&i.Network,
			&i.Nickname,
			&i.Last4,
			&i.CreditLimitCents,
			&i.ClosingDay,
			&i.DueDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallments = `-- name: ListInstallments :many

SELECT i.id, i.ledger_id, i.plan_id, i.installment_no, i.due_month, i.amount_cents, i.status, i.posted_transaction_id, i.paid_statement_id, i.created_at, i.updated_at
FROM installments i
JOIN installment_plans p ON p.id = i.plan_id
WHERE i.ledger_id = $1 AND p.card_account_id = $2
  AND ($3::date IS NULL OR i.due_month = $3)
  AND ($4::text IS NULL OR i.status = $4)
ORDER BY i.due_month, i.installment_no
`

type ListInstallmentsParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	Column3       pgtype.Date
	Column4       string
}

// Installments
func (q *Queries) ListInstallments(ctx context.Context, arg ListInstallmentsParams) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallments,
		arg.LedgerID,
		arg.CardAccountID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.PlanID,
			&i.InstallmentNo,
			&i.DueMonth,
			&i.AmountCents,
			&i.Status,
			&i.PostedTransactionID,
			&i.PaidStatementID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsForPosting = `-- name: ListInstallmentsForPosting :many
SELECT i.id, i.ledger_id, i.plan_id, i.installment_no, i.due_month, i.amount_cents, i.status, i.posted_transaction_id, i.paid_statement_id, i.created_at, i.updated_at
FROM installments i
JOIN installment_plans p ON p.id = i.plan_id
WHERE i.ledger_id = $1
  AND p.card_account_id = $2
  AND i.due_month = $3
  AND i.status = 'scheduled'
ORDER BY i.installment_no
`

type ListInstallmentsForPostingParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	DueMonth      pgtype.Date
}

func (q *Queries) ListInstallmentsForPosting(ctx context.Context, arg ListInstallmentsForPostingParams) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsForPosting, arg.LedgerID, arg.CardAccountID, arg.DueMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.PlanID,
			&i.InstallmentNo,
			&i.DueMonth,
			&i.AmountCents,
			&i.Status,
			&i.PostedTransactionID,
			&i.PaidStatementID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, ledger_id, card_account_id, purchase_occurred_at, merchant, description, category_id, total_amount_cents, installments_count, installment_amount_cents, first_due_month, status, created_by_user_id, created_at, updated_at
FROM installment_plans
WHERE ledger_id = $1 AND card_account_id = $2
  AND ($3::text IS NULL OR status = $3)
ORDER BY created_at DESC
`

type ListPlansParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	Column3       string
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]InstallmentPlan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.LedgerID, arg.CardAccountID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPlan
	for rows.Next() {
		var i InstallmentPlan
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.CardAccountID,
			&i.PurchaseOccurredAt,
			&i.Merchant,
			&i.Description,
			&i.CategoryID,
			&i.TotalAmountCents,
			&i.InstallmentsCount,
			&i.InstallmentAmountCents,
			&i.FirstDueMonth,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatements = `-- name: ListStatements :many
SELECT id, ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id, created_at, updated_at
FROM credit_card_statements
WHERE ledger_id = $1 AND card_account_id = $2
  AND ($3::date IS NULL OR statement_month = $3)
ORDER BY statement_month DESC
`

type ListStatementsParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	Column3       pgtype.Date
}

func (q *Queries) ListStatements(ctx context.Context, arg ListStatementsParams) ([]CreditCardStatement, error) {
	rows, err := q.db.Query(ctx, listStatements, arg.LedgerID, arg.CardAccountID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditCardStatement
	for rows.Next() {
		var i CreditCardStatement
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.CardAccountID,
			&i.StatementMonth,
			&i.ClosingDate,
			&i.DueDate,
			&i.TotalChargesCents,
			&i.TotalPaymentsCents,
			&i.Status,
			&i.PaymentTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallmentPosted = `-- name: MarkInstallmentPosted :exec
UPDATE installments
SET status = 'posted', posted_transaction_id = $2, updated_at = $3
WHERE ledger_id = $1 AND id = $4 AND status = 'scheduled'
`

type MarkInstallmentPostedParams struct {
	LedgerID            pgtype.UUID
	PostedTransactionID pgtype.UUID
	UpdatedAt           pgtype.Timestamptz
	ID                  pgtype.UUID
}

func (q *Queries) MarkInstallmentPosted(ctx context.Context, arg MarkInstallmentPostedParams) error {
	_, err := q.db.Exec(ctx, markInstallmentPosted,
		arg.LedgerID,
		arg.PostedTransactionID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markInstallmentsPaid = `-- name: MarkInstallmentsPaid :exec
UPDATE installments i
SET status = 'paid', paid_statement_id = $4, updated_at = $5
FROM installment_plans p
WHERE i.plan_id = p.id
  AND i.ledger_id = $1
  AND p.card_account_id = $2
  AND i.due_month = $3
  AND i.status = 'posted'
`

type MarkInstallmentsPaidParams struct {
	LedgerID        pgtype.UUID
	CardAccountID   pgtype.UUID
	DueMonth        pgtype.Date
	PaidStatementID pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) MarkInstallmentsPaid(ctx context.Context, arg MarkInstallmentsPaidParams) error {
	_, err := q.db.Exec(ctx, markInstallmentsPaid,
		arg.LedgerID,
		arg.CardAccountID,
		arg.DueMonth,
		arg.PaidStatementID,
		arg.UpdatedAt,
	)
	return err
}

const setStatementPayment = `-- name: SetStatementPayment :one
UPDATE credit_card_statements
SET payment_transaction_id = $2, total_payments_cents = $3, status = $4, updated_at = $5
WHERE id = $1
RETURNING id, ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id, created_at, updated_at
`

type SetStatementPaymentParams struct {
	ID                   pgtype.UUID
	PaymentTransactionID pgtype.UUID
	TotalPaymentsCents   int64
	Status               string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) SetStatementPayment(ctx context.Context, arg SetStatementPaymentParams) (CreditCardStatement, error) {
	row := q.db.QueryRow(ctx, setStatementPayment,
		arg.ID,
		arg.PaymentTransactionID,
		arg.TotalPaymentsCents,
		arg.Status,
		arg.UpdatedAt,
	)
	var i CreditCardStatement
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.StatementMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalChargesCents,
		&i.TotalPaymentsCents,
		&i.Status,
		&i.PaymentTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumStatementCharges = `-- name: SumStatementCharges :one
SELECT COALESCE(SUM(i.amount_cents), 0)
FROM installments i
JOIN installment_plans p ON p.id = i.plan_id
WHERE i.ledger_id = $1
  AND p.card_account_id = $2
  AND i.due_month = $3
  AND i.status IN ('posted', 'paid')
`

type SumStatementChargesParams struct {
	LedgerID      pgtype.UUID
	CardAccountID pgtype.UUID
	DueMonth      pgtype.Date
}

func (q *Queries) SumStatementCharges(ctx context.Context, arg SumStatementChargesParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumStatementCharges, arg.LedgerID, arg.CardAccountID, arg.DueMonth)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateCardNetwork = `-- name: UpdateCardNetwork :one
UPDATE card_networks
SET display_name = $2, updated_at = $3
WHERE code = $1
RETURNING code, display_name, created_at, updated_at
`

type UpdateCardNetworkParams struct {
	Code        string
	DisplayName string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateCardNetwork(ctx context.Context, arg UpdateCardNetworkParams) (CardNetwork, error) {
	row := q.db.QueryRow(ctx, updateCardNetwork, arg.Code, arg.DisplayName, arg.UpdatedAt)
	var i CardNetwork
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreditCard = `-- name: UpdateCreditCard :one
UPDATE credit_cards
SET issuer_name = $2, network = $3, nickname = $4, last4 = $5, credit_limit_cents = $6, closing_day = $7, due_day = $8, updated_at = $9
WHERE account_id = $1
RETURNING account_id, issuer_name, network, nickname, last4, credit_limit_cents, closing_day, due_day, created_at, updated_at
`

type UpdateCreditCardParams struct {
	AccountID        pgtype.UUID
	IssuerName       pgtype.Text
	Network          string
	Nickname         pgtype.Text
	Last4            pgtype.Text
	CreditLimitCents pgtype.Int8
	ClosingDay       int32
	DueDay           int32
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateCreditCard(ctx context.Context, arg UpdateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, updateCreditCard,
		arg.AccountID,
		arg.IssuerName,
		arg.Network,
		arg.Nickname,
		arg.Last4,
		arg.CreditLimitCents,
		arg.ClosingDay,
		arg.DueDay,
		arg.UpdatedAt,
	)
	var i CreditCard
	err := row.Scan(
		&i.AccountID,
		&i.IssuerName,
		&i.Network,
		&i.Nickname,
		&i.Last4,
		&i.CreditLimitCents,
		&i.ClosingDay,
		&i.DueDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstallmentStatus = `-- name: UpdateInstallmentStatus :one
UPDATE installments
SET status = $2, updated_at = $3
WHERE ledger_id = $1 AND id = $4
RETURNING id, ledger_id, plan_id, installment_no, due_month, amount_cents, status, posted_transaction_id, paid_statement_id, created_at, updated_at
`

type UpdateInstallmentStatusParams struct {
	LedgerID  pgtype.UUID
	Status    string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateInstallmentStatus(ctx context.Context, arg UpdateInstallmentStatusParams) (Installment, error) {
	row := q.db.QueryRow(ctx, updateInstallmentStatus,
		arg.LedgerID,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.PlanID,
		&i.InstallmentNo,
		&i.DueMonth,
		&i.AmountCents,
		&i.Status,
		&i.PostedTransactionID,
		&i.PaidStatementID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :exec
UPDATE installment_plans
SET status = $2, updated_at = $3
WHERE ledger_id = $1 AND id = $4
`

type UpdatePlanStatusParams struct {
	LedgerID  pgtype.UUID
	Status    string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error {
	_, err := q.db.Exec(ctx, updatePlanStatus,
		arg.LedgerID,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateStatementTotals = `-- name: UpdateStatementTotals :one
UPDATE credit_card_statements
SET total_charges_cents = $2, total_payments_cents = $3, status = $4, updated_at = $5
WHERE id = $1
RETURNING id, ledger_id, card_account_id, statement_month, closing_date, due_date, total_charges_cents, total_payments_cents, status, payment_transaction_id, created_at, updated_at
`

type UpdateStatementTotalsParams struct {
	ID                 pgtype.UUID
	TotalChargesCents  int64
	TotalPaymentsCents int64
	Status             string
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateStatementTotals(ctx context.Context, arg UpdateStatementTotalsParams) (CreditCardStatement, error) {
	row := q.db.QueryRow(ctx, updateStatementTotals,
		arg.ID,
		arg.TotalChargesCents,
		arg.TotalPaymentsCents,
		arg.Status,
		arg.UpdatedAt,
	)
	var i CreditCardStatement
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.CardAccountID,
		&i.StatementMonth,
		&i.ClosingDate,
		&i.DueDate,
		&i.TotalChargesCents,
		&i.TotalPaymentsCents,
		&i.Status,
		&i.PaymentTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
