// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash_flows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCashFlowEntry = `-- name: CreateCashFlowEntry :one
INSERT INTO cashflow_entries (
  transaction_id,
  category_id,
  payment_method_id,
  installment_plan_id,
  installment_plan_item_id,
  direction,
  title,
  amount,
  is_fixed,
  occurred_at,
  reversal_of_entry_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING cashflow_entry_id, transaction_id, category_id, payment_method_id, installment_plan_id, installment_plan_item_id, direction, title, amount, is_fixed, occurred_at, reversal_of_entry_id, created_at, updated_at
`

type CreateCashFlowEntryParams struct {
	TransactionID         int32
	CategoryID            int32
	PaymentMethodID       int32
	InstallmentPlanID     pgtype.Int4
	InstallmentPlanItemID pgtype.Int4
	Direction             string
	Title                 string
	Amount                pgtype.Numeric
	IsFixed               bool
	OccurredAt            pgtype.Date
	ReversalOfEntryID     pgtype.Int4
}

func (q *Queries) CreateCashFlowEntry(ctx context.Context, arg CreateCashFlowEntryParams) (CashflowEntry, error) {
	row := q.db.QueryRow(ctx, createCashFlowEntry,
		arg.TransactionID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.InstallmentPlanID,
		arg.InstallmentPlanItemID,
		arg.Direction,
		arg.Title,
		arg.Amount,
		arg.IsFixed,
		arg.OccurredAt,
		arg.ReversalOfEntryID,
	)
	var i CashflowEntry
	err := row.Scan(
		&i.CashflowEntryID,
		&i.TransactionID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.InstallmentPlanID,
		&i.InstallmentPlanItemID,
		&i.Direction,
		&i.Title,
		&i.Amount,
		&i.IsFixed,
		&i.OccurredAt,
		&i.ReversalOfEntryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCashFlowEntry = `-- name: DeleteCashFlowEntry :exec
DELETE FROM cashflow_entries
WHERE cashflow_entry_id = $1
`

func (q *Queries) DeleteCashFlowEntry(ctx context.Context, cashflowEntryID int32) error {
	_, err := q.db.Exec(ctx, deleteCashFlowEntry, cashflowEntryID)
	return err
}

const getCashFlowEntry = `-- name: GetCashFlowEntry :one
SELECT
  ce.cashflow_entry_id, ce.transaction_id, ce.category_id, ce.payment_method_id, ce.installment_plan_id, ce.installment_plan_item_id, ce.direction, ce.title, ce.amount, ce.is_fixed, ce.occurred_at, ce.reversal_of_entry_id, ce.created_at, ce.updated_at,
  c.name AS category_name,
  pm.name AS payment_method_name
FROM cashflow_entries ce
JOIN categories c ON c.category_id = ce.category_id
JOIN payment_methods pm ON pm.payment_method_id = ce.payment_method_id
WHERE ce.cashflow_entry_id = $1
`

type GetCashFlowEntryRow struct {
	CashflowEntryID       int32
	TransactionID         int32
	CategoryID            int32
	PaymentMethodID       int32
	InstallmentPlanID     pgtype.Int4
	InstallmentPlanItemID pgtype.Int4
	Direction             string
	Title                 string
	Amount                pgtype.Numeric
	IsFixed               bool
	OccurredAt            pgtype.Date
	ReversalOfEntryID     pgtype.Int4
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	CategoryName          string
	PaymentMethodName     string
}

func (q *Queries) GetCashFlowEntry(ctx context.Context, cashflowEntryID int32) (GetCashFlowEntryRow, error) {
	row := q.db.QueryRow(ctx, getCashFlowEntry, cashflowEntryID)
	var i GetCashFlowEntryRow
	err := row.Scan(
		&i.CashflowEntryID,
		&i.TransactionID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.InstallmentPlanID,
		&i.InstallmentPlanItemID,
		&i.Direction,
		&i.Title,
		&i.Amount,
		&i.IsFixed,
		&i.OccurredAt,
		&i.ReversalOfEntryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.PaymentMethodName,
	)
	return i, err
}

const getCategorySummary = `-- name: GetCategorySummary :many
SELECT
  c.name,
  c.direction,
  COALESCE(
    SUM(
      CASE
        WHEN c.direction = 'IN' AND p.side = 'CREDIT' THEN p.amount
        WHEN c.direction = 'IN' AND p.side = 'DEBIT' THEN -p.amount
        WHEN c.direction = 'OUT' AND p.side = 'DEBIT' THEN p.amount
        WHEN c.direction = 'OUT' AND p.side = 'CREDIT' THEN -p.amount
        ELSE 0
      END
    ),
    0
  )::float AS total_amount
FROM postings p
JOIN transactions t ON t.transaction_id = p.transaction_id
JOIN categories c ON c.category_id = p.category_id
WHERE date_trunc('month', t.occurred_at) = date_trunc('month', $1::date)
  AND c.is_budget_relevant = true
GROUP BY c.name, c.direction
ORDER BY total_amount DESC
`

type GetCategorySummaryRow struct {
	Name        string
	Direction   string
	TotalAmount float64
}

func (q *Queries) GetCategorySummary(ctx context.Context, dollar_1 pgtype.Date) ([]GetCategorySummaryRow, error) {
	rows, err := q.db.Query(ctx, getCategorySummary, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategorySummaryRow
	for rows.Next() {
		var i GetCategorySummaryRow
		if err := rows.Scan(&i.Name, &i.Direction, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
SELECT
  COALESCE(
    SUM(
      CASE
        WHEN c.direction = 'IN' AND p.side = 'CREDIT' THEN p.amount
        WHEN c.direction = 'IN' AND p.side = 'DEBIT' THEN -p.amount
        ELSE 0
      END
    ),
    0
  )::float AS total_income,
  COALESCE(
    SUM(
      CASE
        WHEN c.direction = 'OUT' AND p.side = 'DEBIT' THEN p.amount
        WHEN c.direction = 'OUT' AND p.side = 'CREDIT' THEN -p.amount
        ELSE 0
      END
    ),
    0
  )::float AS total_expense
FROM postings p
JOIN transactions t ON t.transaction_id = p.transaction_id
JOIN categories c ON c.category_id = p.category_id
WHERE date_trunc('month', t.occurred_at) = date_trunc('month', $1::date)
  AND c.is_budget_relevant = true
`

type GetMonthlySummaryRow struct {
	TotalIncome  float64
	TotalExpense float64
}

func (q *Queries) GetMonthlySummary(ctx context.Context, dollar_1 pgtype.Date) (GetMonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary, dollar_1)
	var i GetMonthlySummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const listCashFlowEntriesByMonth = `-- name: ListCashFlowEntriesByMonth :many
WITH picuinha_category AS (
  SELECT category_id
  FROM categories
  WHERE name = 'Picuinhas'
  LIMIT 1
),
combined AS (
  SELECT
    ce.cashflow_entry_id,
    ce.transaction_id,
    ce.category_id,
    ce.payment_method_id,
    ce.installment_plan_id,
    ce.installment_plan_item_id,
    ce.direction,
    ce.title,
    ce.amount,
    ce.is_fixed,
    ce.occurred_at,
    ce.reversal_of_entry_id,
    ce.created_at,
    ce.updated_at
  FROM cashflow_entries ce
  WHERE date_trunc('month', ce.occurred_at) = date_trunc('month', $1::date)

  UNION ALL

  SELECT
    -i.installment_plan_item_id AS cashflow_entry_id,
    COALESCE(i.transaction_id, 0) AS transaction_id,
    COALESCE(p.category_id, (SELECT category_id FROM picuinha_category)) AS category_id,
    COALESCE(p.payment_method_id, 0) AS payment_method_id,
    p.installment_plan_id,
    i.installment_plan_item_id,
    c.direction,
    CASE
      WHEN p.installment_count IS NOT NULL THEN
        CONCAT(p.description, ' (', i.sequence, '/', p.installment_count, ')')
      ELSE
        p.description
    END AS title,
    (i.amount + i.extra_amount) AS amount,
    false AS is_fixed,
    i.due_date AS occurred_at,
    NULL::int AS reversal_of_entry_id,
    i.created_at,
    i.updated_at
  FROM installment_plan_items i
  JOIN installment_plans p ON p.installment_plan_id = i.installment_plan_id
  LEFT JOIN cashflow_entries ce ON ce.installment_plan_item_id = i.installment_plan_item_id
  JOIN categories c ON c.category_id = COALESCE(p.category_id, (SELECT category_id FROM picuinha_category))
  WHERE ce.cashflow_entry_id IS NULL
    AND date_trunc('month', i.due_date) = date_trunc('month', $1::date)
)
SELECT
  combined.cashflow_entry_id, combined.transaction_id, combined.category_id, combined.payment_method_id, combined.installment_plan_id, combined.installment_plan_item_id, combined.direction, combined.title, combined.amount, combined.is_fixed, combined.occurred_at, combined.reversal_of_entry_id, combined.created_at, combined.updated_at,
  c.name AS category_name,
  COALESCE(pm.name, 'Sem meio') AS payment_method_name
FROM combined
JOIN categories c ON c.category_id = combined.category_id
LEFT JOIN payment_methods pm ON pm.payment_method_id = combined.payment_method_id
WHERE ($2::varchar IS NULL OR combined.direction = $2)
  AND ($3::boolean IS NULL OR combined.is_fixed = $3)
ORDER BY combined.occurred_at, combined.cashflow_entry_id
`

type ListCashFlowEntriesByMonthParams struct {
	Column1   pgtype.Date
	Direction pgtype.Text
	IsFixed   pgtype.Bool
}

type ListCashFlowEntriesByMonthRow struct {
	CashflowEntryID       int32
	TransactionID         int32
	CategoryID            int32
	PaymentMethodID       int32
	InstallmentPlanID     pgtype.Int4
	InstallmentPlanItemID pgtype.Int4
	Direction             string
	Title                 string
	Amount                pgtype.Numeric
	IsFixed               bool
	OccurredAt            pgtype.Date
	ReversalOfEntryID     pgtype.Int4
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	CategoryName          string
	PaymentMethodName     string
}

func (q *Queries) ListCashFlowEntriesByMonth(ctx context.Context, arg ListCashFlowEntriesByMonthParams) ([]ListCashFlowEntriesByMonthRow, error) {
	rows, err := q.db.Query(ctx, listCashFlowEntriesByMonth, arg.Column1, arg.Direction, arg.IsFixed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCashFlowEntriesByMonthRow
	for rows.Next() {
		var i ListCashFlowEntriesByMonthRow
		if err := rows.Scan(
			&i.CashflowEntryID,
			&i.TransactionID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.InstallmentPlanID,
			&i.InstallmentPlanItemID,
			&i.Direction,
			&i.Title,
			&i.Amount,
			&i.IsFixed,
			&i.OccurredAt,
			&i.ReversalOfEntryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.PaymentMethodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCashFlowEntry = `-- name: UpdateCashFlowEntry :one
UPDATE cashflow_entries
SET transaction_id = $2,
    category_id = $3,
    payment_method_id = $4,
    installment_plan_id = $5,
    installment_plan_item_id = $6,
    direction = $7,
    title = $8,
    amount = $9,
    is_fixed = $10,
    occurred_at = $11,
    reversal_of_entry_id = $12,
    updated_at = now()
WHERE cashflow_entry_id = $1
RETURNING cashflow_entry_id, transaction_id, category_id, payment_method_id, installment_plan_id, installment_plan_item_id, direction, title, amount, is_fixed, occurred_at, reversal_of_entry_id, created_at, updated_at
`

type UpdateCashFlowEntryParams struct {
	CashflowEntryID       int32
	TransactionID         int32
	CategoryID            int32
	PaymentMethodID       int32
	InstallmentPlanID     pgtype.Int4
	InstallmentPlanItemID pgtype.Int4
	Direction             string
	Title                 string
	Amount                pgtype.Numeric
	IsFixed               bool
	OccurredAt            pgtype.Date
	ReversalOfEntryID     pgtype.Int4
}

func (q *Queries) UpdateCashFlowEntry(ctx context.Context, arg UpdateCashFlowEntryParams) (CashflowEntry, error) {
	row := q.db.QueryRow(ctx, updateCashFlowEntry,
		arg.CashflowEntryID,
		arg.TransactionID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.InstallmentPlanID,
		arg.InstallmentPlanItemID,
		arg.Direction,
		arg.Title,
		arg.Amount,
		arg.IsFixed,
		arg.OccurredAt,
		arg.ReversalOfEntryID,
	)
	var i CashflowEntry
	err := row.Scan(
		&i.CashflowEntryID,
		&i.TransactionID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.InstallmentPlanID,
		&i.InstallmentPlanItemID,
		&i.Direction,
		&i.Title,
		&i.Amount,
		&i.IsFixed,
		&i.OccurredAt,
		&i.ReversalOfEntryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
