// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
  name,
  direction,
  is_budget_relevant,
  is_active
) VALUES (
  $1, $2, $3, $4
)
RETURNING category_id, name, direction, is_budget_relevant, is_active, inactive_from_month
`

type CreateCategoryParams struct {
	Name             string
	Direction        string
	IsBudgetRelevant bool
	IsActive         bool
}

type CreateCategoryRow struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	InactiveFromMonth pgtype.Date
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Direction,
		arg.IsBudgetRelevant,
		arg.IsActive,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.InactiveFromMonth,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :one
UPDATE categories
SET is_active = false,
    inactive_from_month = $2
WHERE category_id = $1
RETURNING category_id, name, direction, is_budget_relevant, is_active, inactive_from_month
`

type DeactivateCategoryParams struct {
	CategoryID        int32
	InactiveFromMonth pgtype.Date
}

type DeactivateCategoryRow struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	InactiveFromMonth pgtype.Date
}

func (q *Queries) DeactivateCategory(ctx context.Context, arg DeactivateCategoryParams) (DeactivateCategoryRow, error) {
	row := q.db.QueryRow(ctx, deactivateCategory, arg.CategoryID, arg.InactiveFromMonth)
	var i DeactivateCategoryRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.InactiveFromMonth,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT category_id, name, direction, is_budget_relevant, is_active, inactive_from_month
FROM categories
WHERE category_id = $1
`

type GetCategoryByIDRow struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	InactiveFromMonth pgtype.Date
}

func (q *Queries) GetCategoryByID(ctx context.Context, categoryID int32) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, categoryID)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.InactiveFromMonth,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, name, direction, is_budget_relevant, is_active, inactive_from_month
FROM categories
WHERE ($1::boolean = false OR is_active = true)
ORDER BY name
`

type ListCategoriesRow struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	InactiveFromMonth pgtype.Date
}

func (q *Queries) ListCategories(ctx context.Context, dollar_1 bool) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Direction,
			&i.IsBudgetRelevant,
			&i.IsActive,
			&i.InactiveFromMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByMonth = `-- name: ListCategoriesByMonth :many
SELECT category_id, name, direction, is_budget_relevant, is_active, inactive_from_month
FROM categories c
WHERE (
  $1::boolean = false
  OR c.is_active = true
  OR EXISTS (
    SELECT 1
    FROM budget_items bi
    JOIN budget_periods bp ON bp.budget_period_id = bi.budget_period_id
    WHERE bi.category_id = c.category_id
      AND date_trunc('month', bp.month) = date_trunc('month', $2::date)
  )
)
AND (
  c.inactive_from_month IS NULL
  OR c.inactive_from_month > $2::date
  OR EXISTS (
    SELECT 1
    FROM budget_items bi
    JOIN budget_periods bp ON bp.budget_period_id = bi.budget_period_id
    WHERE bi.category_id = c.category_id
      AND date_trunc('month', bp.month) = date_trunc('month', $2::date)
  )
)
ORDER BY name
`

type ListCategoriesByMonthParams struct {
	Column1 bool
	Column2 pgtype.Date
}

type ListCategoriesByMonthRow struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	InactiveFromMonth pgtype.Date
}

func (q *Queries) ListCategoriesByMonth(ctx context.Context, arg ListCategoriesByMonthParams) ([]ListCategoriesByMonthRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByMonth, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesByMonthRow
	for rows.Next() {
		var i ListCategoriesByMonthRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Direction,
			&i.IsBudgetRelevant,
			&i.IsActive,
			&i.InactiveFromMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2,
    direction = $3,
    is_budget_relevant = $4,
    is_active = $5
WHERE category_id = $1
RETURNING category_id, name, direction, is_budget_relevant, is_active, inactive_from_month
`

type UpdateCategoryParams struct {
	CategoryID       int32
	Name             string
	Direction        string
	IsBudgetRelevant bool
	IsActive         bool
}

type UpdateCategoryRow struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	InactiveFromMonth pgtype.Date
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.CategoryID,
		arg.Name,
		arg.Direction,
		arg.IsBudgetRelevant,
		arg.IsActive,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Direction,
		&i.IsBudgetRelevant,
		&i.IsActive,
		&i.InactiveFromMonth,
	)
	return i, err
}
