// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallmentPlan = `-- name: CreateInstallmentPlan :one
INSERT INTO installment_plans (
  description,
  plan_type,
  total_amount,
  installment_count,
  installment_amount,
  start_date,
  payment_method_id,
  account_id,
  category_id,
  starts_on_current_invoice
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING installment_plan_id, description, plan_type, total_amount, installment_count, installment_amount, start_date, payment_method_id, account_id, category_id, party_id, interest_rate, recurrence_interval_months, is_active, created_at, updated_at, interest_rate_unit, starts_on_current_invoice
`

type CreateInstallmentPlanParams struct {
	Description            string
	PlanType               string
	TotalAmount            pgtype.Numeric
	InstallmentCount       pgtype.Int4
	InstallmentAmount      pgtype.Numeric
	StartDate              pgtype.Date
	PaymentMethodID        pgtype.Int4
	AccountID              pgtype.Int4
	CategoryID             pgtype.Int4
	StartsOnCurrentInvoice bool
}

func (q *Queries) CreateInstallmentPlan(ctx context.Context, arg CreateInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, createInstallmentPlan,
		arg.Description,
		arg.PlanType,
		arg.TotalAmount,
		arg.InstallmentCount,
		arg.InstallmentAmount,
		arg.StartDate,
		arg.PaymentMethodID,
		arg.AccountID,
		arg.CategoryID,
		arg.StartsOnCurrentInvoice,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.InstallmentPlanID,
		&i.Description,
		&i.PlanType,
		&i.TotalAmount,
		&i.InstallmentCount,
		&i.InstallmentAmount,
		&i.StartDate,
		&i.PaymentMethodID,
		&i.AccountID,
		&i.CategoryID,
		&i.PartyID,
		&i.InterestRate,
		&i.RecurrenceIntervalMonths,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestRateUnit,
		&i.StartsOnCurrentInvoice,
	)
	return i, err
}

const createInstallmentPlanItem = `-- name: CreateInstallmentPlanItem :one
INSERT INTO installment_plan_items (
  installment_plan_id,
  sequence,
  due_date,
  amount,
  status,
  transaction_id,
  extra_amount,
  is_paid,
  paid_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING installment_plan_item_id, installment_plan_id, sequence, due_date, amount, status, transaction_id, created_at, updated_at, extra_amount, is_paid, paid_at
`

type CreateInstallmentPlanItemParams struct {
	InstallmentPlanID int32
	Sequence          int32
	DueDate           pgtype.Date
	Amount            pgtype.Numeric
	Status            string
	TransactionID     pgtype.Int4
	ExtraAmount       pgtype.Numeric
	IsPaid            bool
	PaidAt            pgtype.Timestamptz
}

func (q *Queries) CreateInstallmentPlanItem(ctx context.Context, arg CreateInstallmentPlanItemParams) (InstallmentPlanItem, error) {
	row := q.db.QueryRow(ctx, createInstallmentPlanItem,
		arg.InstallmentPlanID,
		arg.Sequence,
		arg.DueDate,
		arg.Amount,
		arg.Status,
		arg.TransactionID,
		arg.ExtraAmount,
		arg.IsPaid,
		arg.PaidAt,
	)
	var i InstallmentPlanItem
	err := row.Scan(
		&i.InstallmentPlanItemID,
		&i.InstallmentPlanID,
		&i.Sequence,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraAmount,
		&i.IsPaid,
		&i.PaidAt,
	)
	return i, err
}
