// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO accounts (name, type, currency, is_active)
VALUES ($1, $2, $3, $4)
RETURNING account_id, name, type, currency, is_active, created_at, updated_at
`

type CreateLedgerAccountParams struct {
	Name     string
	Type     string
	Currency string
	IsActive bool
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerPosting = `-- name: CreateLedgerPosting :one
INSERT INTO postings (transaction_id, account_id, category_id, party_id, side, amount, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING posting_id, transaction_id, account_id, category_id, party_id, side, amount, memo, created_at
`

type CreateLedgerPostingParams struct {
	TransactionID int32
	AccountID     int32
	CategoryID    pgtype.Int4
	PartyID       pgtype.Int4
	Side          string
	Amount        pgtype.Numeric
	Memo          pgtype.Text
}

func (q *Queries) CreateLedgerPosting(ctx context.Context, arg CreateLedgerPostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, createLedgerPosting,
		arg.TransactionID,
		arg.AccountID,
		arg.CategoryID,
		arg.PartyID,
		arg.Side,
		arg.Amount,
		arg.Memo,
	)
	var i Posting
	err := row.Scan(
		&i.PostingID,
		&i.TransactionID,
		&i.AccountID,
		&i.CategoryID,
		&i.PartyID,
		&i.Side,
		&i.Amount,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :one
INSERT INTO transactions (occurred_at, description, reference, notes)
VALUES ($1, $2, $3, $4)
RETURNING transaction_id, occurred_at, description, reference, notes, created_at, updated_at
`

type CreateLedgerTransactionParams struct {
	OccurredAt  pgtype.Date
	Description string
	Reference   pgtype.Text
	Notes       pgtype.Text
}

func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createLedgerTransaction,
		arg.OccurredAt,
		arg.Description,
		arg.Reference,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OccurredAt,
		&i.Description,
		&i.Reference,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT account_id, name, type, currency, is_active, created_at, updated_at
FROM accounts
ORDER BY name
`

func (q *Queries) ListLedgerAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.AccountID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerPostingsByTransaction = `-- name: ListLedgerPostingsByTransaction :many
SELECT posting_id, transaction_id, account_id, category_id, party_id, side, amount, memo, created_at
FROM postings
WHERE transaction_id = $1
ORDER BY posting_id
`

func (q *Queries) ListLedgerPostingsByTransaction(ctx context.Context, transactionID int32) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listLedgerPostingsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.PostingID,
			&i.TransactionID,
			&i.AccountID,
			&i.CategoryID,
			&i.PartyID,
			&i.Side,
			&i.Amount,
			&i.Memo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerTransactionsByMonth = `-- name: ListLedgerTransactionsByMonth :many
SELECT transaction_id, occurred_at, description, reference, notes, created_at, updated_at
FROM transactions
WHERE occurred_at >= $1
  AND occurred_at < ($1 + interval '1 month')
ORDER BY occurred_at DESC, transaction_id DESC
`

func (q *Queries) ListLedgerTransactionsByMonth(ctx context.Context, occurredAt pgtype.Date) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listLedgerTransactionsByMonth, occurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.OccurredAt,
			&i.Description,
			&i.Reference,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedgerAccount = `-- name: UpdateLedgerAccount :one
UPDATE accounts
SET name = $2,
    type = $3,
    is_active = $4,
    updated_at = now()
WHERE account_id = $1
RETURNING account_id, name, type, currency, is_active, created_at, updated_at
`

type UpdateLedgerAccountParams struct {
	AccountID int32
	Name      string
	Type      string
	IsActive  bool
}

func (q *Queries) UpdateLedgerAccount(ctx context.Context, arg UpdateLedgerAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateLedgerAccount,
		arg.AccountID,
		arg.Name,
		arg.Type,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
