// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID int32
	Name      string
	Type      string
	Currency  string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BudgetItem struct {
	BudgetItemID   int32
	BudgetPeriodID int32
	CategoryID     int32
	Mode           string
	PlannedAmount  pgtype.Numeric
	TargetPercent  pgtype.Numeric
	Notes          pgtype.Text
}

type BudgetPeriod struct {
	BudgetPeriodID int32
	Month          pgtype.Date
	AnalysisMode   pgtype.Text
	IsClosed       bool
}

type Category struct {
	CategoryID        int32
	Name              string
	Direction         string
	IsBudgetRelevant  bool
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	InactiveFromMonth pgtype.Date
}

type InstallmentPlan struct {
	InstallmentPlanID        int32
	Description              string
	PlanType                 string
	TotalAmount              pgtype.Numeric
	InstallmentCount         pgtype.Int4
	InstallmentAmount        pgtype.Numeric
	StartDate                pgtype.Date
	PaymentMethodID          pgtype.Int4
	AccountID                pgtype.Int4
	CategoryID               pgtype.Int4
	PartyID                  pgtype.Int4
	InterestRate             pgtype.Numeric
	RecurrenceIntervalMonths pgtype.Int4
	IsActive                 bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type InstallmentPlanItem struct {
	InstallmentPlanItemID int32
	InstallmentPlanID     int32
	Sequence              int32
	DueDate               pgtype.Date
	Amount                pgtype.Numeric
	Status                string
	TransactionID         pgtype.Int4
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Party struct {
	PartyID   int32
	Name      string
	Kind      string
	Notes     pgtype.Text
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type PaymentMethod struct {
	PaymentMethodID int32
	AccountID       int32
	Name            string
	Kind            string
	BankName        pgtype.Text
	ClosingDay      pgtype.Int4
	DueDay          pgtype.Int4
	CreditLimit     pgtype.Numeric
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Posting struct {
	PostingID     int32
	TransactionID int32
	AccountID     int32
	CategoryID    pgtype.Int4
	PartyID       pgtype.Int4
	Side          string
	Amount        pgtype.Numeric
	Memo          pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type PostingTag struct {
	PostingID int32
	TagID     int32
}

type Tag struct {
	TagID     int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Transaction struct {
	TransactionID int32
	OccurredAt    pgtype.Date
	Description   string
	Reference     pgtype.Text
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
