// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (account_id, name, kind, bank_name, credit_limit, closing_day, due_day, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING payment_method_id, account_id, name, kind, bank_name, closing_day, due_day, credit_limit, is_active, created_at, updated_at
`

type CreatePaymentMethodParams struct {
	AccountID   int32
	Name        string
	Kind        string
	BankName    pgtype.Text
	CreditLimit pgtype.Numeric
	ClosingDay  pgtype.Int4
	DueDay      pgtype.Int4
	IsActive    bool
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.AccountID,
		arg.Name,
		arg.Kind,
		arg.BankName,
		arg.CreditLimit,
		arg.ClosingDay,
		arg.DueDay,
		arg.IsActive,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.PaymentMethodID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.BankName,
		&i.ClosingDay,
		&i.DueDay,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceEntries = `-- name: GetInvoiceEntries :many
SELECT
    i.installment_plan_item_id,
    i.due_date,
    CASE
        WHEN p.installment_count IS NOT NULL AND p.installment_count > 1 THEN
            p.description || ' (' || i.sequence || '/' || p.installment_count || ')'
        ELSE
            p.description
    END AS title,
    (i.amount + i.extra_amount) AS amount,
    COALESCE(c.name, '') AS category_name
FROM installment_plan_items i
JOIN installment_plans p ON p.installment_plan_id = i.installment_plan_id
LEFT JOIN categories c ON c.category_id = p.category_id
WHERE p.payment_method_id = $1
  AND DATE_TRUNC('month', i.due_date) = DATE_TRUNC('month', $2::date)
  AND p.is_active = true
  AND i.status <> 'CANCELED'
ORDER BY i.due_date ASC, i.sequence ASC
`

type GetInvoiceEntriesParams struct {
	PaymentMethodID pgtype.Int4
	Column2         pgtype.Date
}

type GetInvoiceEntriesRow struct {
	InstallmentPlanItemID int32
	DueDate               pgtype.Date
	Title                 interface{}
	Amount                int32
	CategoryName          string
}

func (q *Queries) GetInvoiceEntries(ctx context.Context, arg GetInvoiceEntriesParams) ([]GetInvoiceEntriesRow, error) {
	rows, err := q.db.Query(ctx, getInvoiceEntries, arg.PaymentMethodID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoiceEntriesRow
	for rows.Next() {
		var i GetInvoiceEntriesRow
		if err := rows.Scan(
			&i.InstallmentPlanItemID,
			&i.DueDate,
			&i.Title,
			&i.Amount,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutstandingAmount = `-- name: GetOutstandingAmount :one
SELECT COALESCE(SUM(i.amount + i.extra_amount), 0)::float
FROM installment_plan_items i
JOIN installment_plans p ON p.installment_plan_id = i.installment_plan_id
WHERE p.payment_method_id = $1
  AND DATE_TRUNC('month', i.due_date) >= DATE_TRUNC('month', $2::date)
  AND p.is_active = true
  AND i.status <> 'CANCELED'
  AND i.is_paid = false
`

type GetOutstandingAmountParams struct {
	PaymentMethodID pgtype.Int4
	Column2         pgtype.Date
}

func (q *Queries) GetOutstandingAmount(ctx context.Context, arg GetOutstandingAmountParams) (float64, error) {
	row := q.db.QueryRow(ctx, getOutstandingAmount, arg.PaymentMethodID, arg.Column2)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT payment_method_id, account_id, name, kind, bank_name, closing_day, due_day, credit_limit, is_active, created_at, updated_at
FROM payment_methods
WHERE payment_method_id = $1
`

func (q *Queries) GetPaymentMethod(ctx context.Context, paymentMethodID int32) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, paymentMethodID)
	var i PaymentMethod
	err := row.Scan(
		&i.PaymentMethodID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.BankName,
		&i.ClosingDay,
		&i.DueDay,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT payment_method_id, account_id, name, kind, bank_name, closing_day, due_day, credit_limit, is_active, created_at, updated_at
FROM payment_methods
WHERE ($1::boolean IS NULL OR is_active = $1)
ORDER BY name
`

func (q *Queries) ListPaymentMethods(ctx context.Context, isActive pgtype.Bool) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.AccountID,
			&i.Name,
			&i.Kind,
			&i.BankName,
			&i.ClosingDay,
			&i.DueDay,
			&i.CreditLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods
SET account_id = $2,
    name = $3,
    kind = $4,
    bank_name = $5,
    credit_limit = $6,
    closing_day = $7,
    due_day = $8,
    is_active = $9
WHERE payment_method_id = $1
RETURNING payment_method_id, account_id, name, kind, bank_name, closing_day, due_day, credit_limit, is_active, created_at, updated_at
`

type UpdatePaymentMethodParams struct {
	PaymentMethodID int32
	AccountID       int32
	Name            string
	Kind            string
	BankName        pgtype.Text
	CreditLimit     pgtype.Numeric
	ClosingDay      pgtype.Int4
	DueDay          pgtype.Int4
	IsActive        bool
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.PaymentMethodID,
		arg.AccountID,
		arg.Name,
		arg.Kind,
		arg.BankName,
		arg.CreditLimit,
		arg.ClosingDay,
		arg.DueDay,
		arg.IsActive,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.PaymentMethodID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.BankName,
		&i.ClosingDay,
		&i.DueDay,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
