// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: picuinhas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCasesByPerson = `-- name: CountCasesByPerson :one
SELECT COUNT(*)
FROM installment_plans
WHERE party_id = $1
`

func (q *Queries) CountCasesByPerson(ctx context.Context, partyID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countCasesByPerson, partyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO parties (name, notes, kind, is_active)
VALUES ($1, $2, 'PERSON', true)
RETURNING party_id, name, notes
`

type CreatePersonParams struct {
	Name  string
	Notes pgtype.Text
}

type CreatePersonRow struct {
	PartyID int32
	Name    string
	Notes   pgtype.Text
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (CreatePersonRow, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.Name, arg.Notes)
	var i CreatePersonRow
	err := row.Scan(&i.PartyID, &i.Name, &i.Notes)
	return i, err
}

const createPicuinhaCase = `-- name: CreatePicuinhaCase :one
INSERT INTO installment_plans (
  party_id,
  description,
  plan_type,
  total_amount,
  installment_count,
  installment_amount,
  start_date,
  payment_method_id,
  category_id,
  interest_rate,
  interest_rate_unit,
  recurrence_interval_months,
  starts_on_current_invoice
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, true)
RETURNING installment_plan_id, description, plan_type, total_amount, installment_count, installment_amount, start_date, payment_method_id, account_id, category_id, party_id, interest_rate, recurrence_interval_months, is_active, created_at, updated_at, interest_rate_unit, starts_on_current_invoice
`

type CreatePicuinhaCaseParams struct {
	PartyID                  pgtype.Int4
	Description              string
	PlanType                 string
	TotalAmount              pgtype.Numeric
	InstallmentCount         pgtype.Int4
	InstallmentAmount        pgtype.Numeric
	StartDate                pgtype.Date
	PaymentMethodID          pgtype.Int4
	CategoryID               pgtype.Int4
	InterestRate             pgtype.Numeric
	InterestRateUnit         pgtype.Text
	RecurrenceIntervalMonths pgtype.Int4
}

func (q *Queries) CreatePicuinhaCase(ctx context.Context, arg CreatePicuinhaCaseParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, createPicuinhaCase,
		arg.PartyID,
		arg.Description,
		arg.PlanType,
		arg.TotalAmount,
		arg.InstallmentCount,
		arg.InstallmentAmount,
		arg.StartDate,
		arg.PaymentMethodID,
		arg.CategoryID,
		arg.InterestRate,
		arg.InterestRateUnit,
		arg.RecurrenceIntervalMonths,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.InstallmentPlanID,
		&i.Description,
		&i.PlanType,
		&i.TotalAmount,
		&i.InstallmentCount,
		&i.InstallmentAmount,
		&i.StartDate,
		&i.PaymentMethodID,
		&i.AccountID,
		&i.CategoryID,
		&i.PartyID,
		&i.InterestRate,
		&i.RecurrenceIntervalMonths,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestRateUnit,
		&i.StartsOnCurrentInvoice,
	)
	return i, err
}

const createPicuinhaCaseInstallment = `-- name: CreatePicuinhaCaseInstallment :one
INSERT INTO installment_plan_items (
  installment_plan_id,
  sequence,
  due_date,
  amount,
  extra_amount,
  is_paid,
  paid_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING installment_plan_item_id, installment_plan_id, sequence, due_date, amount, status, transaction_id, created_at, updated_at, extra_amount, is_paid, paid_at
`

type CreatePicuinhaCaseInstallmentParams struct {
	InstallmentPlanID int32
	Sequence          int32
	DueDate           pgtype.Date
	Amount            pgtype.Numeric
	ExtraAmount       pgtype.Numeric
	IsPaid            bool
	PaidAt            pgtype.Timestamptz
}

func (q *Queries) CreatePicuinhaCaseInstallment(ctx context.Context, arg CreatePicuinhaCaseInstallmentParams) (InstallmentPlanItem, error) {
	row := q.db.QueryRow(ctx, createPicuinhaCaseInstallment,
		arg.InstallmentPlanID,
		arg.Sequence,
		arg.DueDate,
		arg.Amount,
		arg.ExtraAmount,
		arg.IsPaid,
		arg.PaidAt,
	)
	var i InstallmentPlanItem
	err := row.Scan(
		&i.InstallmentPlanItemID,
		&i.InstallmentPlanID,
		&i.Sequence,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraAmount,
		&i.IsPaid,
		&i.PaidAt,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM parties
WHERE party_id = $1
  AND kind = 'PERSON'
`

func (q *Queries) DeletePerson(ctx context.Context, partyID int32) error {
	_, err := q.db.Exec(ctx, deletePerson, partyID)
	return err
}

const deletePicuinhaCase = `-- name: DeletePicuinhaCase :exec
DELETE FROM installment_plans
WHERE installment_plan_id = $1
`

func (q *Queries) DeletePicuinhaCase(ctx context.Context, installmentPlanID int32) error {
	_, err := q.db.Exec(ctx, deletePicuinhaCase, installmentPlanID)
	return err
}

const getPerson = `-- name: GetPerson :one
SELECT party_id, name, notes
FROM parties
WHERE party_id = $1
  AND kind = 'PERSON'
`

type GetPersonRow struct {
	PartyID int32
	Name    string
	Notes   pgtype.Text
}

func (q *Queries) GetPerson(ctx context.Context, partyID int32) (GetPersonRow, error) {
	row := q.db.QueryRow(ctx, getPerson, partyID)
	var i GetPersonRow
	err := row.Scan(&i.PartyID, &i.Name, &i.Notes)
	return i, err
}

const getPersonBalance = `-- name: GetPersonBalance :one
SELECT (
  COALESCE(
    (
      SELECT SUM(i.amount + i.extra_amount)
      FROM installment_plan_items i
      JOIN installment_plans p ON p.installment_plan_id = i.installment_plan_id
      WHERE p.party_id = $1
        AND i.is_paid = false
        AND (
          p.plan_type <> 'RECURRING'
          OR DATE_TRUNC('month', i.due_date) <= DATE_TRUNC('month', CURRENT_DATE)
        )
    ),
    0
  )
)::decimal
`

func (q *Queries) GetPersonBalance(ctx context.Context, partyID pgtype.Int4) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getPersonBalance, partyID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getPicuinhaCase = `-- name: GetPicuinhaCase :one
SELECT installment_plan_id, description, plan_type, total_amount, installment_count, installment_amount, start_date, payment_method_id, account_id, category_id, party_id, interest_rate, recurrence_interval_months, is_active, created_at, updated_at, interest_rate_unit, starts_on_current_invoice
FROM installment_plans
WHERE installment_plan_id = $1
  AND party_id IS NOT NULL
`

func (q *Queries) GetPicuinhaCase(ctx context.Context, installmentPlanID int32) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, getPicuinhaCase, installmentPlanID)
	var i InstallmentPlan
	err := row.Scan(
		&i.InstallmentPlanID,
		&i.Description,
		&i.PlanType,
		&i.TotalAmount,
		&i.InstallmentCount,
		&i.InstallmentAmount,
		&i.StartDate,
		&i.PaymentMethodID,
		&i.AccountID,
		&i.CategoryID,
		&i.PartyID,
		&i.InterestRate,
		&i.RecurrenceIntervalMonths,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestRateUnit,
		&i.StartsOnCurrentInvoice,
	)
	return i, err
}

const getPicuinhaCaseInstallment = `-- name: GetPicuinhaCaseInstallment :one
SELECT installment_plan_item_id, installment_plan_id, sequence, due_date, amount, status, transaction_id, created_at, updated_at, extra_amount, is_paid, paid_at
FROM installment_plan_items
WHERE installment_plan_item_id = $1
`

func (q *Queries) GetPicuinhaCaseInstallment(ctx context.Context, installmentPlanItemID int32) (InstallmentPlanItem, error) {
	row := q.db.QueryRow(ctx, getPicuinhaCaseInstallment, installmentPlanItemID)
	var i InstallmentPlanItem
	err := row.Scan(
		&i.InstallmentPlanItemID,
		&i.InstallmentPlanID,
		&i.Sequence,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraAmount,
		&i.IsPaid,
		&i.PaidAt,
	)
	return i, err
}

const listPersons = `-- name: ListPersons :many
SELECT party_id, name, notes
FROM parties
WHERE kind = 'PERSON'
ORDER BY name
`

type ListPersonsRow struct {
	PartyID int32
	Name    string
	Notes   pgtype.Text
}

func (q *Queries) ListPersons(ctx context.Context) ([]ListPersonsRow, error) {
	rows, err := q.db.Query(ctx, listPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonsRow
	for rows.Next() {
		var i ListPersonsRow
		if err := rows.Scan(&i.PartyID, &i.Name, &i.Notes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPicuinhaCaseInstallments = `-- name: ListPicuinhaCaseInstallments :many
SELECT installment_plan_item_id, installment_plan_id, sequence, due_date, amount, status, transaction_id, created_at, updated_at, extra_amount, is_paid, paid_at
FROM installment_plan_items
WHERE installment_plan_id = $1
ORDER BY due_date ASC, sequence ASC
`

func (q *Queries) ListPicuinhaCaseInstallments(ctx context.Context, installmentPlanID int32) ([]InstallmentPlanItem, error) {
	rows, err := q.db.Query(ctx, listPicuinhaCaseInstallments, installmentPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPlanItem
	for rows.Next() {
		var i InstallmentPlanItem
		if err := rows.Scan(
			&i.InstallmentPlanItemID,
			&i.InstallmentPlanID,
			&i.Sequence,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.TransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExtraAmount,
			&i.IsPaid,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPicuinhaCasesByPerson = `-- name: ListPicuinhaCasesByPerson :many
SELECT
  p.installment_plan_id, p.description, p.plan_type, p.total_amount, p.installment_count, p.installment_amount, p.start_date, p.payment_method_id, p.account_id, p.category_id, p.party_id, p.interest_rate, p.recurrence_interval_months, p.is_active, p.created_at, p.updated_at, p.interest_rate_unit, p.starts_on_current_invoice,
  COUNT(i.installment_plan_item_id) AS installments_total,
  COUNT(i.installment_plan_item_id) FILTER (WHERE i.is_paid) AS installments_paid,
  COALESCE(SUM(i.amount + i.extra_amount) FILTER (WHERE i.is_paid), 0)::decimal AS amount_paid,
  COALESCE(SUM(i.amount + i.extra_amount) FILTER (WHERE NOT i.is_paid), 0)::decimal AS amount_remaining
FROM installment_plans p
LEFT JOIN installment_plan_items i ON i.installment_plan_id = p.installment_plan_id
WHERE p.party_id = $1
GROUP BY p.installment_plan_id
ORDER BY p.created_at DESC
`

type ListPicuinhaCasesByPersonRow struct {
	InstallmentPlanID        int32
	Description              string
	PlanType                 string
	TotalAmount              pgtype.Numeric
	InstallmentCount         pgtype.Int4
	InstallmentAmount        pgtype.Numeric
	StartDate                pgtype.Date
	PaymentMethodID          pgtype.Int4
	AccountID                pgtype.Int4
	CategoryID               pgtype.Int4
	PartyID                  pgtype.Int4
	InterestRate             pgtype.Numeric
	RecurrenceIntervalMonths pgtype.Int4
	IsActive                 bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	InterestRateUnit         pgtype.Text
	StartsOnCurrentInvoice   bool
	InstallmentsTotal        int64
	InstallmentsPaid         int64
	AmountPaid               pgtype.Numeric
	AmountRemaining          pgtype.Numeric
}

func (q *Queries) ListPicuinhaCasesByPerson(ctx context.Context, partyID pgtype.Int4) ([]ListPicuinhaCasesByPersonRow, error) {
	rows, err := q.db.Query(ctx, listPicuinhaCasesByPerson, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPicuinhaCasesByPersonRow
	for rows.Next() {
		var i ListPicuinhaCasesByPersonRow
		if err := rows.Scan(
			&i.InstallmentPlanID,
			&i.Description,
			&i.PlanType,
			&i.TotalAmount,
			&i.InstallmentCount,
			&i.InstallmentAmount,
			&i.StartDate,
			&i.PaymentMethodID,
			&i.AccountID,
			&i.CategoryID,
			&i.PartyID,
			&i.InterestRate,
			&i.RecurrenceIntervalMonths,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InterestRateUnit,
			&i.StartsOnCurrentInvoice,
			&i.InstallmentsTotal,
			&i.InstallmentsPaid,
			&i.AmountPaid,
			&i.AmountRemaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE parties
SET name = $2,
    notes = $3
WHERE party_id = $1
  AND kind = 'PERSON'
RETURNING party_id, name, notes
`

type UpdatePersonParams struct {
	PartyID int32
	Name    string
	Notes   pgtype.Text
}

type UpdatePersonRow struct {
	PartyID int32
	Name    string
	Notes   pgtype.Text
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (UpdatePersonRow, error) {
	row := q.db.QueryRow(ctx, updatePerson, arg.PartyID, arg.Name, arg.Notes)
	var i UpdatePersonRow
	err := row.Scan(&i.PartyID, &i.Name, &i.Notes)
	return i, err
}

const updatePicuinhaCase = `-- name: UpdatePicuinhaCase :one
UPDATE installment_plans
SET party_id = $2,
    description = $3,
    plan_type = $4,
    total_amount = $5,
    installment_count = $6,
    installment_amount = $7,
    start_date = $8,
    payment_method_id = $9,
    category_id = $10,
    interest_rate = $11,
    interest_rate_unit = $12,
    recurrence_interval_months = $13
WHERE installment_plan_id = $1
RETURNING installment_plan_id, description, plan_type, total_amount, installment_count, installment_amount, start_date, payment_method_id, account_id, category_id, party_id, interest_rate, recurrence_interval_months, is_active, created_at, updated_at, interest_rate_unit, starts_on_current_invoice
`

type UpdatePicuinhaCaseParams struct {
	InstallmentPlanID        int32
	PartyID                  pgtype.Int4
	Description              string
	PlanType                 string
	TotalAmount              pgtype.Numeric
	InstallmentCount         pgtype.Int4
	InstallmentAmount        pgtype.Numeric
	StartDate                pgtype.Date
	PaymentMethodID          pgtype.Int4
	CategoryID               pgtype.Int4
	InterestRate             pgtype.Numeric
	InterestRateUnit         pgtype.Text
	RecurrenceIntervalMonths pgtype.Int4
}

func (q *Queries) UpdatePicuinhaCase(ctx context.Context, arg UpdatePicuinhaCaseParams) (InstallmentPlan, error) {
	row := q.db.QueryRow(ctx, updatePicuinhaCase,
		arg.InstallmentPlanID,
		arg.PartyID,
		arg.Description,
		arg.PlanType,
		arg.TotalAmount,
		arg.InstallmentCount,
		arg.InstallmentAmount,
		arg.StartDate,
		arg.PaymentMethodID,
		arg.CategoryID,
		arg.InterestRate,
		arg.InterestRateUnit,
		arg.RecurrenceIntervalMonths,
	)
	var i InstallmentPlan
	err := row.Scan(
		&i.InstallmentPlanID,
		&i.Description,
		&i.PlanType,
		&i.TotalAmount,
		&i.InstallmentCount,
		&i.InstallmentAmount,
		&i.StartDate,
		&i.PaymentMethodID,
		&i.AccountID,
		&i.CategoryID,
		&i.PartyID,
		&i.InterestRate,
		&i.RecurrenceIntervalMonths,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InterestRateUnit,
		&i.StartsOnCurrentInvoice,
	)
	return i, err
}

const updatePicuinhaCaseInstallment = `-- name: UpdatePicuinhaCaseInstallment :one
UPDATE installment_plan_items
SET amount = $2,
    extra_amount = $3,
    is_paid = $4,
    paid_at = $5
WHERE installment_plan_item_id = $1
RETURNING installment_plan_item_id, installment_plan_id, sequence, due_date, amount, status, transaction_id, created_at, updated_at, extra_amount, is_paid, paid_at
`

type UpdatePicuinhaCaseInstallmentParams struct {
	InstallmentPlanItemID int32
	Amount                pgtype.Numeric
	ExtraAmount           pgtype.Numeric
	IsPaid                bool
	PaidAt                pgtype.Timestamptz
}

func (q *Queries) UpdatePicuinhaCaseInstallment(ctx context.Context, arg UpdatePicuinhaCaseInstallmentParams) (InstallmentPlanItem, error) {
	row := q.db.QueryRow(ctx, updatePicuinhaCaseInstallment,
		arg.InstallmentPlanItemID,
		arg.Amount,
		arg.ExtraAmount,
		arg.IsPaid,
		arg.PaidAt,
	)
	var i InstallmentPlanItem
	err := row.Scan(
		&i.InstallmentPlanItemID,
		&i.InstallmentPlanID,
		&i.Sequence,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraAmount,
		&i.IsPaid,
		&i.PaidAt,
	)
	return i, err
}
