// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package auth

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOwnerMember = `-- name: AddOwnerMember :exec
INSERT INTO ledger_members (ledger_id, user_id, role, updated_at)
VALUES ($1, $2, 'owner', $3)
`

type AddOwnerMemberParams struct {
	LedgerID  pgtype.UUID
	UserID    pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) AddOwnerMember(ctx context.Context, arg AddOwnerMemberParams) error {
	_, err := q.db.Exec(ctx, addOwnerMember, arg.LedgerID, arg.UserID, arg.UpdatedAt)
	return err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :one

INSERT INTO auth_identities (user_id, provider, provider_user_id, email, email_verified, last_login_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), $6)
RETURNING id, user_id, provider, provider_user_id, COALESCE(email, ''), email_verified, last_login_at
`

type CreateAuthIdentityParams struct {
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	EmailVerified  bool
	UpdatedAt      pgtype.Timestamptz
}

type CreateAuthIdentityRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          string
	EmailVerified  bool
	LastLoginAt    pgtype.Timestamptz
}

// Auth: identities
func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (CreateAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.EmailVerified,
		arg.UpdatedAt,
	)
	var i CreateAuthIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerified,
		&i.LastLoginAt,
	)
	return i, err
}

const createAuthSecret = `-- name: CreateAuthSecret :exec

INSERT INTO auth_secrets (user_id, password_hash, updated_at)
VALUES ($1, $2, $3)
`

type CreateAuthSecretParams struct {
	UserID       pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

// Auth: secrets
func (q *Queries) CreateAuthSecret(ctx context.Context, arg CreateAuthSecretParams) error {
	_, err := q.db.Exec(ctx, createAuthSecret, arg.UserID, arg.PasswordHash, arg.UpdatedAt)
	return err
}

const createAuthSession = `-- name: CreateAuthSession :one

INSERT INTO auth_sessions (user_id, refresh_token_hash, expires_at, user_agent, ip, device_name, rotated_from_session_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, expires_at, revoked_at
`

type CreateAuthSessionParams struct {
	UserID               pgtype.UUID
	RefreshTokenHash     string
	ExpiresAt            pgtype.Timestamptz
	UserAgent            pgtype.Text
	Ip                   pgtype.Text
	DeviceName           pgtype.Text
	RotatedFromSessionID pgtype.UUID
	UpdatedAt            pgtype.Timestamptz
}

type CreateAuthSessionRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

// Auth: sessions
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
		arg.DeviceName,
		arg.RotatedFromSessionID,
		arg.UpdatedAt,
	)
	var i CreateAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createLedgerForUser = `-- name: CreateLedgerForUser :one

INSERT INTO ledgers (owner_user_id, name, currency_code)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateLedgerForUserParams struct {
	OwnerUserID  pgtype.UUID
	Name         string
	CurrencyCode string
}

// Ledgers: default ledger creation on signup
func (q *Queries) CreateLedgerForUser(ctx context.Context, arg CreateLedgerForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createLedgerForUser, arg.OwnerUserID, arg.Name, arg.CurrencyCode)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createOAuthState = `-- name: CreateOAuthState :one

INSERT INTO oauth_states (provider, state, code_verifier, redirect_uri, expires_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider, state, code_verifier, redirect_uri, expires_at, used_at
`

type CreateOAuthStateParams struct {
	Provider     string
	State        string
	CodeVerifier string
	RedirectUri  pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CreateOAuthStateRow struct {
	ID           pgtype.UUID
	Provider     string
	State        string
	CodeVerifier string
	RedirectUri  pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
}

// Auth: oauth states
func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (CreateOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, createOAuthState,
		arg.Provider,
		arg.State,
		arg.CodeVerifier,
		arg.RedirectUri,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	var i CreateOAuthStateRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.State,
		&i.CodeVerifier,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, display_name, avatar_url, email_verified_at, is_active, updated_at)
VALUES ($1, $2, $3, $4, COALESCE($5, true), $6)
RETURNING id, email, COALESCE(display_name, ''), COALESCE(avatar_url, ''), email_verified_at, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email           string
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	Column5         interface{}
	UpdatedAt       pgtype.Timestamptz
}

type CreateUserRow struct {
	ID              pgtype.UUID
	Email           string
	DisplayName     string
	AvatarUrl       string
	EmailVerifiedAt pgtype.Timestamptz
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Auth: users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.EmailVerifiedAt,
		arg.Column5,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthIdentityByProvider = `-- name: GetAuthIdentityByProvider :one
SELECT id, user_id, provider, provider_user_id, COALESCE(email, ''), email_verified, last_login_at
FROM auth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetAuthIdentityByProviderParams struct {
	Provider       string
	ProviderUserID string
}

type GetAuthIdentityByProviderRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          string
	EmailVerified  bool
	LastLoginAt    pgtype.Timestamptz
}

func (q *Queries) GetAuthIdentityByProvider(ctx context.Context, arg GetAuthIdentityByProviderParams) (GetAuthIdentityByProviderRow, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i GetAuthIdentityByProviderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.EmailVerified,
		&i.LastLoginAt,
	)
	return i, err
}

const getAuthSecretHash = `-- name: GetAuthSecretHash :one
SELECT password_hash
FROM auth_secrets
WHERE user_id = $1
`

func (q *Queries) GetAuthSecretHash(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAuthSecretHash, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getAuthSessionByRefreshHash = `-- name: GetAuthSessionByRefreshHash :one
SELECT id, user_id, expires_at, revoked_at
FROM auth_sessions
WHERE refresh_token_hash = $1
`

type GetAuthSessionByRefreshHashRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) GetAuthSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (GetAuthSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByRefreshHash, refreshTokenHash)
	var i GetAuthSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthState = `-- name: GetOAuthState :one
SELECT id, provider, state, code_verifier, redirect_uri, expires_at, used_at
FROM oauth_states
WHERE state = $1
`

type GetOAuthStateRow struct {
	ID           pgtype.UUID
	Provider     string
	State        string
	CodeVerifier string
	RedirectUri  pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
}

func (q *Queries) GetOAuthState(ctx context.Context, state string) (GetOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, getOAuthState, state)
	var i GetOAuthStateRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.State,
		&i.CodeVerifier,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, COALESCE(display_name, ''), COALESCE(avatar_url, ''), email_verified_at, is_active, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              pgtype.UUID
	Email           string
	DisplayName     string
	AvatarUrl       string
	EmailVerifiedAt pgtype.Timestamptz
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, COALESCE(display_name, ''), COALESCE(avatar_url, ''), email_verified_at, is_active, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              pgtype.UUID
	Email           string
	DisplayName     string
	AvatarUrl       string
	EmailVerifiedAt pgtype.Timestamptz
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthSessionsByUser = `-- name: ListAuthSessionsByUser :many
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at, user_agent, ip, device_name, created_at, updated_at, rotated_from_session_id
FROM auth_sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAuthSessionsByUserRow struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	RefreshTokenHash     string
	ExpiresAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	UserAgent            pgtype.Text
	Ip                   pgtype.Text
	DeviceName           pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RotatedFromSessionID pgtype.UUID
}

func (q *Queries) ListAuthSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListAuthSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAuthSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthSessionsByUserRow
	for rows.Next() {
		var i ListAuthSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserAgent,
			&i.Ip,
			&i.DeviceName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RotatedFromSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthSessionByRefreshHash = `-- name: LockAuthSessionByRefreshHash :one
SELECT id, user_id, expires_at, revoked_at
FROM auth_sessions
WHERE refresh_token_hash = $1
FOR UPDATE
`

type LockAuthSessionByRefreshHashRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) LockAuthSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (LockAuthSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, lockAuthSessionByRefreshHash, refreshTokenHash)
	var i LockAuthSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const markOAuthStateUsed = `-- name: MarkOAuthStateUsed :exec
UPDATE oauth_states
SET used_at = now(), updated_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkOAuthStateUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOAuthStateUsed, id)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const revokeAllAuthSessionsForUser = `-- name: RevokeAllAuthSessionsForUser :exec
UPDATE auth_sessions
SET revoked_at = now(), updated_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAuthSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAuthSessionsForUser, userID)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = now(), updated_at = now()
WHERE refresh_token_hash = $1
`

func (q *Queries) RevokeAuthSession(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, refreshTokenHash)
	return err
}

const revokeAuthSessionByID = `-- name: RevokeAuthSessionByID :exec
UPDATE auth_sessions
SET revoked_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeAuthSessionByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionByID, id)
	return err
}

const updateAuthIdentityLogin = `-- name: UpdateAuthIdentityLogin :exec
UPDATE auth_identities
SET last_login_at = now(), updated_at = now()
WHERE user_id = $1 AND provider = $2
`

type UpdateAuthIdentityLoginParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) UpdateAuthIdentityLogin(ctx context.Context, arg UpdateAuthIdentityLoginParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityLogin, arg.UserID, arg.Provider)
	return err
}

const updateAuthSecret = `-- name: UpdateAuthSecret :exec
UPDATE auth_secrets
SET password_hash = $2, updated_at = $3
WHERE user_id = $1
`

type UpdateAuthSecretParams struct {
	UserID       pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateAuthSecret(ctx context.Context, arg UpdateAuthSecretParams) error {
	_, err := q.db.Exec(ctx, updateAuthSecret, arg.UserID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
